Repository Seagate/cortx-motr, pull requests merged in 2021-03, with the labels that each got.

#469 [ARM porting] Required code changes to fix build issues
  configure.ac
  cortx-motr.spec.in
  lib/trace.h
  lib/user_space/user_x86_64_atomic.h
  m0t1fs/linux_kernel/dir.c
  m0t1fs/linux_kernel/inode.c
  motr/linux_kernel/m0tr_main.c
  net/lnet/ut/lnet_ut.c
  ut/linux_kernel/m0ut_main.c
Labels: cla-signed

#409 EOS-16743: Add an API for getting the max segment size for a domain
  motr/ut/cs_ut_main.c
  net/bulk_emulation/mem_xprt_xo.c
  net/lnet/lnet_xo.c
  net/net.c
  net/net.h
  net/sock/sock.c
  rpc/rpc.c
  rpc/rpc_machine.c
Labels: cla-signed

#462 EOS-18124: ISA-L - Implement encode function
  sns/parity_math.c
  sns/parity_math.h
Labels: cla-signed, isal_integration

#468 Quick-Start-Guide.rst: fix Prerequisites section
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#478 EOS-18056 : Fix bulk-server-ut and bulk-client-ut.
  ioservice/ut/bulkio_common.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#483 Fix m0_op_io::ioo_ivec field name in comments
  motr/client_internal.h
  motr/pg.h
Labels: cla-signed

#477 EOS-18067 : Mini-provisionor changes in cortex-motr repo
  Makefile.am
  python3.6
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup.py
Labels: cla-signed

#480 EOS-16473,EOS-17618: [DTM0] Implement persistent log
  be/dtm0_log.c
  be/dtm0_log.h
  be/ut/dtm0_log_ut.c
Labels: cla-signed

#476 EOS-17584 dtm0: implement initial version of all2all connections
  dtm0/service.c
  dtm0/service.h
  dtm0/ut/main.c
  motr/ut/idx_dix.c
  pool/pool.c
Labels: cla-signed

#481 EOS-17642: implement an integration test for all2all connections
  dtm0/it/all2all/all2all
  dtm0/it/all2all/test.yaml
  motr/st/utils/ha_msg_send.sh
Labels: cla-signed

#495 Update Quick-Start-Guide.rst
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#497 EOS 18061 - Fix spiel ut failures for libfabric transport
  net/libfab/libfab.c
  rpc/rpc.c
  sns/cm/repair/ut/net.c
Labels: cla-signed, libfabric_integration

#484 EOS-17630: [DTM0] Handle P notice on the client.
  be/dtm0_log.c
  be/dtm0_log.h
  be/ut/dtm0_log_ut.c
  cas/service.c
  dtm0/clk_src.c
  dtm0/clk_src.h
  dtm0/doc/dtx.txt
  dtm0/dtx.c
  dtm0/dtx.h
  dtm0/fop.c
  dtm0/fop.h
  dtm0/service.c
  dtm0/service.h
  dtm0/tx_desc.c
  dtm0/tx_desc.h
  dtm0/ut/clk_src_ut.c
  motr/idx_dix.c
  motr/ut/dix_conf.cg
  motr/ut/idx_dix.c
  utils/trace/m0trace
Labels: cla-signed

#488 Auto Assign Reviewers
  .github/auto_assign.yml
Labels: cla-signed

#461 m0crate kv(index) test fixes.
  motr/m0crate/crate.c
  motr/m0crate/crate_client.h
  motr/m0crate/crate_index.c
  motr/m0crate/parser.c
  motr/m0crate/scripts/README.md
  motr/m0crate/scripts/gen_index_yaml_run_workload
  motr/m0crate/scripts/m0crate-index.yaml.template
  motr/m0crate/tests/test1.yaml
  motr/m0crate/tests/test2.yaml
  motr/m0crate/tests/test3.yaml
  motr/m0crate/tests/test4.yaml
  motr/m0crate/tests/test5.yaml
  motr/m0crate/tests/test6.yaml
Labels: cla-signed

#506 EOS-18627: Add more UTs for happy-path.
  motr/ut/idx_dix.c
Labels: cla-signed

#515 Update CODEOWNERS
  CODEOWNERS
Labels: cla-signed

#500 EOS-18762 : Use two local endpoints for two way connection establishment in libfabric transport
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#528 Update dix_repair_st.sh
  dix/cm/st/dix_repair_st.sh
Labels: cla-signed

#532 Update motr-ci-workflow.rst
  doc/ci_doc/motr-ci-workflow.rst
Labels: cla-signed

#533 Update motr-single_tests.yaml
  .xperior/testds/motr-single_tests.yaml
Labels: cla-signed

#511 EOS-18604: Uniform distribution of CAS FOM locality index
  cas/service.c
  fop/fom.c
  fop/fom.h
  fop/fom_generic.c
Labels: cla-signed

#534 DTM0: Fix plog initialization.
  dtm0/helper.c
  dtm0/service.c
Labels: cla-signed

#487 client-io: simplify pargrp_iomap_init
  motr/io_pargrp.c
  motr/ut/io_pargrp.c
Labels: cla-signed

#522 added state diagrams of deletion and iteration operation
  btree/btree.c
Labels: cla-signed

#510 Clearing up optional builds
  doc/Quick-Start-Guide.rst
Labels: cla-signed, needs-attention

#518 Update dtm-hld.org
  doc/dev/dtm/dtm-hld.org
Labels: cla-signed

#543 [DTM0] EOS-17644: add the client to all2all integration test
  dtm0/it/all2all/README.md
  dtm0/it/all2all/all2all
  dtm0/it/all2all/cdf.yaml
  dtm0/it/all2all/hare.patch
  dtm0/it/all2all/m0crate.yaml
  motr/client_init.c
  pool/pool.c
Labels: cla-signed

#536 EOS-18144: template files for all provisioner stage
  scripts/install/opt/seagate/cortx/motr/conf/motr.config.tmpl
  scripts/install/opt/seagate/cortx/motr/conf/motr.config.tmpl.sample
  scripts/install/opt/seagate/cortx/motr/conf/motr.post_install.tmpl
  scripts/install/opt/seagate/cortx/motr/conf/motr.post_install.tmpl.sample
  scripts/install/opt/seagate/cortx/motr/conf/motr.prepare.tmpl
  scripts/install/opt/seagate/cortx/motr/conf/motr.prepare.tmpl.sample
  scripts/install/opt/seagate/cortx/motr/conf/motr.test.tmpl
  scripts/install/opt/seagate/cortx/motr/conf/motr.test.tmpl.sample
  scripts/install/opt/seagate/cortx/motr/conf/setup.yaml
Labels: cla-signed

#529 EOS-18144: Modified motr mini provisioner according to new conf store keys
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
  scripts/install/opt/seagate/cortx/motr/conf/examples/provisioner_cluster.json
Labels: cla-signed

#547 EOS-17644 dtm0: override m0crate cfg in all2all test
  dtm0/it/all2all/README.md
  dtm0/it/all2all/all2all
  dtm0/it/all2all/m0crate.yaml.in
Labels: cla-signed

#535 m0crate: fix segv crash when MOTR_CONFIG is missing
  motr/m0crate/parser.c
Labels: cla-signed

#541 EOS-18776: bulk-server-ut fails with --enable-data-integrity
  file/file.c
  ioservice/ut/bulkio_ut.c
Labels: cla-signed

#527 [DTM0] EOS-18811: Finalize DTX when it enters DONE state.
  be/dtm0_log.c
  be/dtm0_log.h
  dtm0/dtx.c
  dtm0/dtx.h
  dtm0/fop.c
  motr/idx.c
Labels: cla-signed

#555 [DTM0] EOS-18958: Add ADDB2 instrumentation
  addb2/dump.c
  addb2/identifier.h
  cas/service.c
  dtm0/Makefile.sub
  dtm0/addb2.h
  dtm0/dtx.c
  dtm0/fop.c
  dtm0/fop.h
  dtm0/service.c
  motr/idx.c
Labels: cla-signed

#486 lib: enhance m0_uint128_sscanf to allow dec/oct formats
  lib/misc.c
  lib/types.h
Labels: cla-signed

#505 EOS-18808 fix panic on rm-rcredits-ut:debtor-death
  rm/ut/rcredits.c
Labels: cla-signed

#554 [DTM0] Use rt checks agains DTM0 configure flag.
  cas/service.c
  configure.ac
  dix/req.c
  dix/ut/client_ut.c
  motr/client_init.c
  motr/idx.c
  motr/ut/idx_dix.c
Labels: cla-signed
