Repository Seagate/cortx-motr, pull requests merged in 2021-12, with the labels that each got.

#1215 EOS-25302 After delete, storage is not reclaimed completely.
  ioservice/ut/bulkio_ut.c
  stob/ad.c
Labels: cla-signed

#1282 Verified Motr QSG
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#1125 EOS-24933: s3server service failing intermittently while executing s3 tests.
  motr/io_req_fop.c
Labels: cla-signed

#1236 Update Quick-Start-Guide.rst
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#1029 Test get Motr ready QSG
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#1285 EOS-26618 dtm0: skip execution of REDO UT if DTM0 is disabled
  motr/ut/idx_dix.c
Labels: cla-signed

#1274 ADDB_Monitoring.md file uploaded.
  doc/ADDB_Monitoring.md
Labels: cla-signed

#1275 AR_RPC_Layer.md file uploaded.
  doc/AR_RPC_Layer.md
Labels: cla-signed

#1276 Build-Environment.md file uploaded
  doc/Build-Environment.md
Labels: cla-signed

#1277 Castor.md file uploaded.
  doc/Castor.md
Labels: cla-signed

#1278 Containers.md file uploaded.
  doc/Containers.md
Labels: cla-signed

#1279 CORTX-MOTR-ARCHITECTURE.md file uploaded.
  doc/CORTX-MOTR-ARCHITECTURE.md
Labels: cla-signed

#1280 Data-Organization.md file uploaded.
  doc/Data-Organization.md
Labels: cla-signed

#1281 DMT.md file uploaded.
  doc/DMT.md
Labels: cla-signed

#1259 EOS 21985 : Remove m0_nanosleep() and instead use fi_trywait() so that epoll_wait() will not run in busy loop.
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
  utils/spiel/m0_filesystem_stats
Labels: cla-signed, libfabric_integration

#1287 EOS-26774: re-enable 23spiel-dix-repair* for libfabric
  .xperior/testds/motr-single_tests.yaml
  scripts/m0
Labels: cla-signed

#1288 rpms: motr without kernel dependencies
  Makefile.am
  configure.ac
  cortx-motr.spec.in
Labels: cla-signed

#1291 EOS-26812 : Increase timeout for sns ST's 60sns-repair-motr-1f in jenkins PR build run.
  .xperior/testds/motr-single_tests.yaml
Labels: cla-signed

#1296 EOS-26265:[F-53B]Add support-bundle framework support from motr side
  scripts/install/opt/seagate/cortx/motr/libexec/m0reportbug-bundler
Labels: cla-signed

#1205 EOS-25516- Remove libfabric rpm package if we want to use lustre
  configure.ac
  cortx-motr.spec.in
  scripts/jenkins/build
Labels: cla-signed

#1258 Update documentation
  README.rst
Labels: cla-signed

#1297 EOS-26847 : Remove asserts for return values of fi_trywait() and epoll_wait().
  net/libfab/libfab.c
Labels: cla-signed, libfabric_integration

#1305 EOS-26309: Btree ut to test crc
  btree/btree.c
Labels: cla-signed, btree_update

#1308 EOS-26716: Update ST files to use the default transport address format
  console/st/console-st.sh
  net/test/st/run-1x1.sh
  net/test/st/st-config.sh.in
  net/test/st/st.sh
  utils/functions
Labels: cla-signed

#1307 EOS-26269 : [F-53B]Support for type based support-bundle filter
  scripts/install/opt/seagate/cortx/motr/libexec/m0reportbug-bundler
  utils/m0reportbug
Labels: cla-signed

#1316 bug fixes for reading objects after cluster reboot
  btree/btree.c
  cas/ctg_store.c
Labels: cla-signed

#1320 EOS-26224- basic balloc/data support with partition stob.
  be/log_store.c
  be/partition_table.c
  be/partition_table.h
  ioservice/storage_dev.c
  ioservice/storage_dev.h
  stob/ioq.c
  stob/partition.c
  stob/partition.h
Labels: cla-signed

#1304 EOS-26667: DTM0 refactored (skel and APIs)
  dtm0/Kbuild.sub
  dtm0/Makefile.sub
  dtm0/cfg_default.c
  dtm0/cfg_default.h
  dtm0/domain.c
  dtm0/domain.h
  dtm0/dtx0.c
  dtm0/dtx0.h
  dtm0/log.c
  dtm0/log.h
  dtm0/net.c
  dtm0/net.h
  dtm0/pmach.c
  dtm0/pmach.h
  dtm0/pruner.c
  dtm0/pruner.h
  dtm0/remach.c
  dtm0/remach.h
  dtm0/ut/Makefile.sub
  dtm0/ut/domain.c
  dtm0/ut/dtx0.c
  dtm0/ut/log.c
  dtm0/ut/main.c
  dtm0/ut/net.c
  dtm0/ut/pmach.c
  dtm0/ut/pruner.c
  dtm0/ut/remach.c
  motr/client_init.c
  motr/client_internal.h
  motr/magic.h
  motr/setup.c
  motr/setup.h
Labels: cla-signed, DTM0

#1294 EOS-24982: motr crash observed in rconfc_herd_cctx_fini
  conf/rconfc.c
Labels: cla-signed

#1323 EOS-25901: M0_CALL log level is incorporated in M0_LOG
  lib/coroutine.c
  lib/coroutine.h
Labels: cla-signed

#1324 EOS-26190:m0_sm_asts_run_function_spams_trace_log_file
  sm/sm.c
Labels: cla-signed

#1327 lib: fix m0_uint128_sscanf() for large values
  lib/misc.c
  lib/types.h
Labels: cla-signed

#1326 EOS-26193:frm_fill_packet_from_item_sources_function_spams_trace_log
  rpc/formation2.c
Labels: cla-signed

#1328 client.h: clarify M0_ENF_META usage doc
  motr/client.h
Labels: cla-signed

#1319 lib: introduce m0_trace_level_allow() API
  bindings/go/mio/mio.go
  lib/trace.c
  lib/trace.h
Labels: cla-signed

#1331 Eos-26175 - Added ut to test CRC when loading btree nodes.
  balloc/balloc.c
  be/extmap.c
  be/tool/beck.c
  btree/btree.c
  btree/btree.h
  cas/ctg_store.c
  cob/cob.c
  conf/db.c
Labels: cla-signed

#1337 Fixing rpm failure
  btree/btree.c
Labels: cla-signed

#1340 vsize changes for internal fixed format node
  btree/btree.c
Labels: cla-signed

#1333 [EOS-25904] support 'data_node' or 'storage_node' as node type
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1309 EOS-26720: fdmi records timeout resend
  .xperior/testds/motr-single_tests.yaml
  fdmi/plugins/fdmi_plugin_st.sh
  fdmi/source_dock.c
  fdmi/source_dock_fom.c
  fdmi/source_dock_internal.h
  fdmi/src_rec.h
  fdmi/ut/sd_release_fom.c
  rpc/conn_pool.c
  rpc/rpc_opcodes.h
Labels: cla-signed

#1334 EOS-23152: Gradual increase in main memory observed
  motr/io_pargrp.c
Labels: cla-signed

#1336 EOS-27025: Memory leak during Degraded Read operation
  motr/io_nw_xfer.c
Labels: cla-signed

#1335 EOS-26326: Implementation of BTREE ENCODED CRC for fixed format node
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#1310 EOS-26908: Use setup_size to set some parameters in deployment phases
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1311 EOS-26241: Set ADDB SIZE to motr config file according to setup_size
  scripts/install/etc/sysconfig/motr
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
Labels: cla-signed

#1345 EOS-26312: enable di flag s3 api motr side changes
  motr/client.h
  motr/client_internal.h
  motr/io.c
  motr/io_nw_xfer.c
  motr/io_req.c
  motr/io_req_fop.c
Labels: cla-signed

#1342 EOS-26987: Implement used space for nodes between low and high watermark
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#1097 EOS-24299: Ignore service failures when parent node is failed/offline
  motr/client_internal.h
  motr/io.c
  motr/io_req.c
  motr/ut/client.h
  motr/ut/io.c
  motr/ut/io_dummy.c
  motr/ut/io_pargrp.c
  motr/ut/io_req.c
  pool/pool.c
  pool/pool.h
  pool/pool_machine.c
  pool/pool_machine.h
Labels: cla-signed

#1303 EOS-25807 : Libfabric address format changes.
  motr/init.c
  net/Makefile.sub
  net/ip.c
  net/ip.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
  net/net.h
  net/test/ut/main.c
  net/test/ut/network.c
Labels: cla-signed, libfabric_integration

#1346 [EOS_27101] UUID parsing failing for klibm0-ut
  ut/m0kut
Labels: cla-signed

#1338 EOS-26270 : [F-53B]Support for core dump include/exclude support-bundle filter
  scripts/install/opt/seagate/cortx/motr/libexec/m0reportbug-bundler
  utils/m0reportbug
Labels: cla-signed

#1347 EOS 24233: Disable checksum verification for degraded read and read verify
  motr/client_internal.h
  motr/io.c
  motr/io_req.c
  motr/io_req_fop.c
Labels: cla-signed

#1348 EOS-27125: Errors in UT io-nw-xfer-ut and m0singlenode script
  motr/ut/io_nw_xfer.c
Labels: cla-signed
