Repository Seagate/cortx-motr, pull requests merged in 2021-11, with the labels that each got.

#1192 Eos 25484: UT for be allocator changes
  be/ut/alloc.c
  be/ut/main.c
Labels: cla-signed

#1033 EOS-24273: improve m0reportbug to collect latest live core
  utils/m0reportbug
Labels: cla-signed, needs-attention

#1194 Ctg extmap bug fixing
  be/extmap.c
  be/extmap.h
  cas/ctg_store.c
  cas/ut/service_ut.c
  stob/ad.c
  stob/domain.c
  stob/domain.h
  stob/type.h
  stob/ut/ad.c
Labels: cla-signed

#1199 Changes in cob to call truncate function before destroy
  cob/cob.c
Labels: cla-signed

#1203 ADDB: set addb log size to 128M for servers to avoid VM space full
  scripts/install/opt/seagate/cortx/motr/conf/motr.conf
Labels: cla-signed

#1204 EOS-25789 : Add retry mechanism for DNS resolution in libfabric.
  motr/motr-pub.api
  net/ip.c
  net/ip.h
  net/libfab/libfab.c
Labels: cla-signed, libfabric_integration

#1187 EOS-25671 FDMI record dtx ref count
  fdmi/fol_fdmi_src.c
  fdmi/plugin_dock.c
  fdmi/plugin_dock_fom.c
  fdmi/source_dock.c
  fdmi/source_dock_fom.c
  fdmi/source_dock_internal.h
  fdmi/ut/fol_ut.c
  fdmi/ut/sd_apply_filter.c
  fdmi/ut/sd_post_record.c
Labels: cla-signed

#1185 EOS-24894: Clean up the clink in rconfc_herd_link_fom_wait_on
  conf/rconfc_link_fom.c
Labels: cla-signed

#1196 EOS-25506: LC : remove m0provision config from rpm spec files
  cortx-motr.spec.in
Labels: cla-signed

#1210 ADDB: setup addb path buffer size to 512 bytes to support long pathname
  motr/setup.c
Labels: cla-signed

#1200 EOS-25789 : Add retry mechanism for fqdn to ip resolution.
  net/libfab/libfab.c
Labels: cla-signed

#1206 EOS-25297 : fix compilation errors with gcc-8 for libfabric
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed

#1217 Fix C++ compiler warnings for public headers
  be/fmt.h
  be/io.h
  be/log.h
  ha/link_fops.h
  lib/bob.h
  lib/ext.h
  lib/time.h
  lib/types.h
Labels: cla-signed

#1202 lib: include config.h automatically
  Makefile.am
  configure.ac
  lib/atomic.h
  lib/vec.h
Labels: cla-signed

#1219 EOS-25890: FDMI plugin failure test in ST
  fdmi/plugins/fdmi_app
  fdmi/plugins/fdmi_plugin_st.sh
Labels: cla-signed

#1221 EOS-25693-new: Support Bundle generation is not creating and collecting data for m0reportbug-traces.
  utils/m0reportbug
Labels: cla-signed

#980 rpc: call ->rio_sent() unconditionally.
  rpc/frmops.c
  rpc/item.c
  rpc/item_internal.h
Labels: cla-signed

#1222 EOS-24240: implementation of m0_net_ip_print() and m0_net_ip_to_hostname()
  net/ip.c
  net/ip.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed

#1229 Revert "rpc: call ->rio_sent() unconditionally."
  rpc/frmops.c
  rpc/item.c
  rpc/item_internal.h
Labels: cla-signed

#1226 EOS-26198: re-enable st 49motr-rpc-cancel for libfabric
  motr/st/utils/motr_rpc_cancel_test.sh
  scripts/m0
Labels: cla-signed

#1232 rconfc: increase rconfc retry to support larger node cluster
  conf/rconfc.c
Labels: cla-signed

#1172 Update Quick-Start-Guide.rst
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#1231 FOL: set FOL_REC_MAXSIZE to support multiple node setup
  fol/fol.h
Labels: cla-signed

#1235 go/mio/README: add info about mkv
  bindings/go/README.md
Labels: cla-signed

#1246 EOS-26562: motr code fails to build if motr/config.h is not found.
  configure.ac
Labels: cla-signed

#1242 EOS-26541: Incorrect check of M0_ENF_META flag in oi_flags field of struct m0_op_idx
  motr/idx_dix.c
Labels: cla-signed

#1245 EOS-26287 FDMI events ack when it is consumed
  fdmi/plugins/fdmi_app
  fdmi/plugins/fdmi_plugin_st.sh
  fdmi/plugins/fdmi_sample_plugin.c
  fdmi/ut/sd_release_fom.c
Labels: cla-signed

#1249 EOS 26216 : Hctl boot strap is stuck in kubernetes branch
  net/libfab/libfab.c
Labels: cla-signed

#1256 EOS-26104 : libfabric-devel is needed for 'make rpms' for motr.
  doc/Quick-Start-Guide.rst
  scripts/provisioning/roles/motr-build/tasks/main.yml
Labels: cla-signed, libfabric_integration

#1175 EOS-25393 dtm0: handling of the payload of the REDO messages
  cas/cas.h
  cas/service.c
  dtm0/drlink.c
  dtm0/dtm0.h
  dtm0/fop.c
  dtm0/fop.h
  motr/ut/idx_dix.c
  rpc/rpc_opcodes.h
Labels: cla-signed

#1218 EOS-22462 dtm0/ut/drlink: send DTM0 messages from server to client
  be/linux_kernel/stubs.c
  dtm0/drlink.c
  dtm0/drlink.h
  dtm0/fop.c
  dtm0/fop.h
  dtm0/linux_kernel/stubs.c
  dtm0/service.h
  dtm0/ut/Makefile.sub
  dtm0/ut/drlink.c
  dtm0/ut/helper.c
  dtm0/ut/helper.h
  dtm0/ut/main.c
Labels: cla-signed, needs-attention

#1257 dtm0: Fix build failure in ut/idx_dix.c
  motr/ut/idx_dix.c
Labels: cla-signed

#1244 EOS-25581 : main/551: m0d panic at m0_tlist_remove after m0_tlist_del
  net/libfab/libfab.c
Labels: cla-signed, libfabric_integration

#1264 go/mio: fix bogus ENOENT error on read
  bindings/go/mio/mio.go
Labels: cla-signed

#1265 Changes to support U16 type in xcode.
  console/console_it.c
  xcode/string.c
  xcode/ut/xcode.c
  xcode/xcode.c
  xcode/xcode.h
Labels: cla-signed

#1252 Eos 26176: UT to test LRU changes
  btree/btree.c
Labels: cla-signed

#1240 EOS-25149: Aligned Chunk header implementation and btree integration.
  be/alloc.c
  be/alloc_internal.h
  be/ut/alloc.c
  be/ut/main.c
  btree/btree.c
Labels: cla-signed

#1250 Eos 26172 : Implementation of write path functions for CRC where CRC is encoded by user
  balloc/balloc.c
  be/extmap.c
  be/tool/beck.c
  btree/btree.c
  btree/btree.h
  cas/ctg_store.c
  cob/cob.c
  conf/db.c
Labels: cla-signed

#1227 EOS-25780: destroy-cortx-cloud.sh script stuck and failed to delete the containers
  Makefile.am
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/usr/libexec/cortx-motr/motr-start
Labels: cla-signed

#1270 EOS-26638: Align metadata size to nearest 4k size
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#1267 EOS-26579:Remove share path from cluster config file due to glusterfs removal
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1271 EOS-26717: print logs to console to be read from kubectl logs command
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#1182 EOS-24233: Reads failed with Internal Error for 1Mb object
  motr/io_nw_xfer.c
Labels: cla-signed

#979 Add proper type for m0_rpc_connection_session_specific_fom::ssf_term_…
  rpc/session_foms.c
  rpc/session_foms.h
Labels: cla-signed, needs-attention

#1261 Store FDMI events in kafka.
  fdmi/plugins/fdmi_app
  fdmi/plugins/fdmi_plugin_st.sh
Labels: cla-signed
