Repository Seagate/cortx-motr, pull requests merged in 2021-02, with the labels that each got.

#378 EOS-16740 : Run net-test:cmd-single ut using libfabric transport
  motr/magic.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
  net/test/ut/commands.c
Labels: cla-signed

#374 provisioner: multinode motr provisioner support added
  cortx-motr.spec.in
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
  scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
Labels: cla-signed

#380 Table alignment
  doc/motr-design-doc-list.rst
Labels: cla-signed

#385 EOS-17063 Libfabric: Run client-server-stub ut using libfabric transport
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#391 DTM0: added configuration parameters for DTM0 service
  conf/objs/service.c
  dtm0/Kbuild.sub
  dtm0/conf.cg
  dtm0/fop.c
  dtm0/service.c
  dtm0/service.h
  fop/fom_generic.c
  motr/ut/dix_conf.cg
Labels: cla-signed

#354 motr.conf: fix performance of a single-threaded client
  scripts/install/opt/seagate/cortx/motr/conf/motr.conf
Labels: cla-signed

#399 provisioner: fixes for motr provisioner CI-CD integration
  cortx-motr.spec.in
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/conf/examples/motr_prov_conf.json
  scripts/install/opt/seagate/cortx/motr/conf/examples/provisioner_cluster.json
  scripts/install/opt/seagate/cortx/motr/conf/setup.yaml
  scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
Labels: cla-signed

#400 provisioner: provisioner_cluster.json added in rpm install
  Makefile.am
Labels: cla-signed

#373 build-prep-1node.sh: improve to use by non-root users
  scripts/provisioning/build-prep-1node.sh
Labels: cla-signed

#340 EOS-16682 "m0 run-ut" fails in repetition run
  addb2/ut/consumer.c
  be/ut/extmap.c
  be/ut/fl.c
  cm/ut/cm.c
  conf/ut/db.c
  conf/ut/rconfc.c
  dix/cm/ut/iter_ut.c
  fdmi/ut/filterc_ut.c
  fdmi/ut/sd_apply_filter.c
  fdmi/ut/sd_common.c
  fdmi/ut/sd_send_not.c
  file/ut/file.c
  fol/ut/fol.c
  ioservice/ut/bulkio_ut.c
  ioservice/ut/cob_foms.c
  lib/ut/lockers.c
  lib/ut/thread_pool.c
  motr/ut/client.c
  net/ut/bulk_if.c
  net/ut/tm_provision_ut.c
  reqh/ut/reqh_fom_ut.c
  rm/ut/rm_service.c
  rpc/session_foms.c
  rpc/ut/formation2.c
  rpc/ut/item.c
  rpc/ut/item_source.c
  sm/ut/sm.c
  sns/cm/repair/ut/storage.c
  sns/cm/repair/ut/xform.c
  sss/ut/sss_ut.c
  ut/m0ut.c
  ut/ut.c
Labels: cla-signed

#408 m0crate: fix operations logging
  motr/m0crate/crate_io.c
Labels: cla-signed

#379 Fix iem alert formatting
  format/format.c
  motr/iem.c
  motr/iem.h
  motr/ut/cs_ut_main.c
Labels: cla-signed

#402 go/mio: fix getOptimalUnitSz to take pool into account
  bindings/go/mio/mio.go
Labels: cla-signed

#393 DTM0: Cleanup, added bob for m0_dtm0_process
  dtm0/service.c
Labels: cla-signed

#362 lib: introduce m0_buf_new_aligned()
  lib/buf.c
  lib/buf.h
Labels: cla-signed

#377 go/README: add a bit more info about mcp
  bindings/go/README.md
Labels: cla-signed

#387 EOS-16459: [DTM0] Implement DTM0 local non-persistent log structure for originators
  be/Makefile.sub
  be/dtm0_log.c
  be/dtm0_log.h
  be/ut/Makefile.sub
  be/ut/dtm0_log_ut.c
  dtm0/tx_desc.c
  dtm0/tx_desc.h
  ut/m0ut.c
Labels: cla-signed

#404 EOS-17032: support meta operations in MD timelines scripts
  scripts/addb-py/chronometry/md_req.py
Labels: cla-signed, needs-attention

#384 EOS-16741: Dynamic registration and deregistration of network transports
  net/net.c
  net/net.h
  net/test/ut/client_server.c
  net/test/ut/main.c
Labels: cla-signed

#412 EOS-16866: [DTM0] DIX with DTX.
  cas/cas.h
  cas/client.c
  cas/service.c
  dix/client.c
  dix/client.h
  dix/req.c
  dtm/dtm.h
  dtm0/Kbuild.sub
  dtm0/Makefile.sub
  dtm0/dtx.c
  dtm0/dtx.h
  dtm0/fop.c
  dtm0/fop.h
  dtm0/service.c
  dtm0/service.h
  motr/client_init.c
  motr/client_internal.h
  motr/idx.c
  motr/idx_dix.c
  motr/ut/idx_dix.c
Labels: cla-signed

#394 Update Quick-Start-Guide.rst
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#413 Fix IEM alert formatting.
  format/format.c
  motr/iem.c
Labels: cla-signed

#228 Doc: PRC Layer core
  doc/Images/layercore.PNG
  doc/Images/processing.PNG
  doc/Images/rpccore.PNG
  doc/RPC_Layer_Core.rst
Labels: WIP, cla-signed

#434 Changes to IEM string for BE error.
  format/format.c
  motr/iem.c
Labels: cla-signed

#430 Add a comment to ioreq_iomaps_parity_groups_cal()
  motr/io_req.c
Labels: cla-signed

#414 EOS-16179:[DTM0]
  cas/client.c
  cas/service.c
  dtm0/dtm0.h
  dtm0/fop.c
  dtm0/fop.h
  dtm0/tx_desc.c
  dtm0/tx_desc.h
  dtm0/ut/main.c
  ut/m0ut.c
Labels: cla-signed

#417 [EOS-17233] Use libfab format EP if libfabric is available
  cas/ut/client_ut.c
  cm/ut/cm.c
  conf/ut/common.h
  console/st/server.c
  console/ut/console.c
  dix/ut/client_ut.c
  fdmi/st/echo/fdmi_echo.c
  fdmi/ut/filterc_ut.c
  ha/ut/note.c
  ioservice/ut/bulkio_common.c
  ioservice/ut/cob_foms.c
  ioservice/ut/ios_buffer_pool.c
  ioservice/ut/storage_dev_ut.c
  iscservice/ut/service_ut.c
  motr/conf.c
  motr/ut/cs_ut_main.c
  motr/ut/idx_dix.c
  net/libfab/libfab.c
  net/module.c
  reqh/ut/service_ctx.c
  rm/ut/rm_service.c
  rpc/it/rpc_ping.c
  rpc/ub/ub.c
  rpc/ut/clnt_srv_ctx.c
  scripts/install/usr/libexec/cortx-motr/motr-server
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
  sns/cm/repair/ut/cp_common.c
  spiel/st/m0t1fs_spiel_st.sh
  spiel/ut/spiel_ut_common.c
  spiel/ut/spiel_ut_common.h
  sss/ut/sss_ut.c
Labels: cla-signed

#437 IEM: changes to message for BE error. (#434)
  format/format.c
  motr/iem.c
Labels: cla-signed

#386 Welcome bot for contributors
  .github/config.yml
Labels: cla-signed

#423 go/README: fix minor wording issue
  bindings/go/README.md
Labels: cla-signed

#449 go/mio: add -Wl,-rpath option for libmotr.so
  bindings/go/mio/mio.go
Labels: cla-signed

#304 RM: fix remote debtors leakage
  doc/Doxyfile
  doc/Images/RM-data-structs.svg
  ha/entrypoint.c
  rm/rm.c
  rm/rm.h
  rm/rm_foms.c
  rm/rm_ha.c
  rm/rm_internal.h
  rm/rm_service.c
  rm/ut/rcredits.c
  rm/ut/rm_foms.c
  rm/ut/rm_fops.c
  rm/ut/rmut.c
  rpc/rev_conn.h
  rpc/service.c
  rpc/service.h
Labels: bug, cla-signed

#451 EOS-18284: add license header to motr_data_recovery.sh file
  scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Labels: cla-signed

#456 EOS-18284: add license header to motr_data_recovery.sh file
  scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Labels: cla-signed

#439 EOS 17064 Libfabric : Run net-test:cmd-multiple ut using libfabric transport
  motr/magic.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
  net/test/ut/commands.c
Labels: cla-signed, libfabric_integration

#455 Update .whitesource
  .whitesource
Labels: cla-signed

#452 EOS-16838 RM: fix remote debtors leakage (#304)
  doc/Doxyfile
  doc/Images/RM-data-structs.svg
  ha/entrypoint.c
  rm/rm.c
  rm/rm.h
  rm/rm_foms.c
  rm/rm_ha.c
  rm/rm_internal.h
  rm/rm_service.c
  rm/ut/rcredits.c
  rm/ut/rm_foms.c
  rm/ut/rm_fops.c
  rm/ut/rmut.c
  rpc/rev_conn.h
  rpc/service.c
  rpc/service.h
Labels: cla-signed

#381 EOS-16937: ADDB stob doesn't contain IO path records
  addb2/global.c
  fop/fom.c
Labels: cla-signed

#457 Update .whitesource
  .whitesource
Labels: cla-signed

#460 Update CODEOWNERS
  CODEOWNERS
Labels: cla-signed

#395 Adding the Fol document and updating the Motr Design Doc List
  doc/HLD_of_FOL.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#396 Adding the HLD of Object Index
  doc/HLD_of_Motr_Object_Index.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#398 Adding the SNS Client Document
  doc/HLD_of_SNS_Client.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#415 Adding the HLD of Catalogue Service
  doc/HLD_of_Catalogue_Service.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#420 Uploading the ISC Service User Guide
  doc/ISC_Service_User_Guide.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#432 Adding the SNS server Document
  doc/HLD_of_SNS_Server.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#446 Adding the Network benchmark Document
  doc/HLD_of_Motr_Network_Benchmark.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#433 Added the Motr Ha interface document
  doc/HLD_of_Motr_HA_Interface.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#435 Adding the Hld auxillary Databases Document
  doc/HLD_of_Auxillary_Databases.rst
Labels: cla-signed

#438 Added the HLD document for Distributed indexing
  doc/HLD_of_Distributed_Indexing.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#440 Added the HLD of Motr Lostore Document
  doc/HLD_of_Motr_Lostore.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#441 Adding the Motr Configuration Caching Document
  doc/HLD_of_Motr_Caching.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#444 Adding the Ar_RPC_Layer Document
  doc/AR_RPC_Layer.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#454 provisioning: fix ansible_user var usage
  scripts/provisioning/client.yml
  scripts/provisioning/roles/base-os/tasks/main.yml
  scripts/provisioning/roles/ssh-jumphost/tasks/main.yml
  scripts/provisioning/roles/ssh-target/tasks/main.yml
  scripts/provisioning/ssu.yml
Labels: cla-signed

#458 provisioning: add StrictHostKeyChecking=no at cmu
  scripts/provisioning/roles/ssh-jumphost/tasks/main.yml
Labels: cla-signed

#463 Update motr-design-doc-list.rst
  doc/motr-design-doc-list.rst
Labels: cla-signed

#422 EOS-16760: configure with variable rpm version
  autogen.sh
  configure.ac
Labels: cla-signed
