Repository Seagate/cortx-motr, pull requests merged in 2021-04, with the labels that each got.

#553 EOS-18144 : Add templates in rpm
  Makefile.am
  scripts/install/opt/seagate/cortx/motr/conf/motr.post_install.tmpl
  scripts/install/opt/seagate/cortx/motr/conf/motr.prepare.tmpl
Labels: cla-signed

#558 Reference $HOME instead of root
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#416 Replace Galois Arithmetic APIs with respective ISA APIs
  Makefile.am
  configure.ac
  cortx-motr.spec.in
  lib/ub.c
  scripts/m0
  scripts/provisioning/roles/motr-build/tasks/isa-l.spec
  scripts/provisioning/roles/motr-build/tasks/main.yml
  scripts/provisioning/roles/motr-build/vars/RedHat.yml
  sns/parity_math.c
  sns/parity_math.h
  sns/parity_ops.c
  sns/parity_ops.h
  sns/ut/parity_math_ut.c
  ut/m0ub.c
Labels: cla-signed, isal_integration

#551 EOS-18144 provisioner: Added support for prepare phase
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#568 EOS-18144 scripts: Added 'TMPL_POOL_TYPE' in template files
  scripts/install/opt/seagate/cortx/motr/conf/motr.post_install.tmpl
  scripts/install/opt/seagate/cortx/motr/conf/motr.prepare.tmpl
Labels: cla-signed

#552 client-io: get rid of redundant code
  m0t1fs/linux_kernel/file.c
  m0t1fs/linux_kernel/ut/file.c
  motr/io.h
  motr/io_nw_xfer.c
  motr/io_pargrp.c
  motr/pg.h
  motr/ut/io.c
  motr/ut/io_pargrp.c
  motr/utils.c
Labels: cla-signed

#569 Update README.md
  dtm0/it/all2all/README.md
Labels: cla-signed

#573 Fix minor typo in text: motr -> Motr
  doc/reading-list.md
Labels: cla-signed

#570 Timeout error fix
  rpc/frmops.c
  scripts/install/opt/seagate/cortx/motr/conf/motr.conf
Labels: cla-signed

#574 mcp: fix output file mode
  bindings/go/mcp/mcp.go
Labels: cla-signed

#560 client-io: split & simplify pargrp_iomap_populate()
  m0t1fs/linux_kernel/file.c
  motr/io_pargrp.c
  motr/io_req.c
  motr/pg.h
Labels: cla-signed

#411 layout: add Access Plan API
  doc/Images/layout-plan-isc-usage.svg
  doc/Images/layout-plan-read-fail.svg
  doc/Images/layout-plan-simple-read.svg
  doc/PDF/layout-access-plan.pdf
  layout/plan.h
  rm/rm.h
Labels: cla-signed

#562 Some introduction PDF files of Motr and HLD of SNS Repair
  doc/HLD_of_SNS_Repair.rst
  doc/Images/Formula-1.PNG
  doc/Images/Formula-2.PNG
  doc/Images/Formula-3.png
  doc/Images/Formula-4.png
  doc/Images/Formula-5.PNG
  doc/Images/MicroscopicState.png
  doc/Images/StateMachine.png
  doc/Images/StateTransition.png
  doc/PDF/SAGE_D3.9_HSM_final_v1.1_PUBLIC.pdf
  doc/PDF/SAGE_D35_HSM_validation_readiness_PUBLIC.pdf
  doc/PDF/SAGE_WP3_HSM_for_SAGE_Concept_and_Architecture_v1_Submitted_PUBLIC.pdf
  doc/PDF/motr_technical_long.pdf
Labels: cla-signed

#581 [DTM0] Fix use-after-free in STABLE.
  motr/idx_dix.c
Labels: cla-signed

#582 [DTM0] EOS-19239: Move op to E state when E_ALL reached.
  motr/idx_dix.c
Labels: cla-signed

#579 doc: generate data-flow UML diagrams online
  doc/data-flow/README.md
  doc/data-flow/s3-0.txt
  doc/data-flow/s3-1.txt
  doc/data-flow/s3-2.txt
Labels: cla-signed

#548 [EOS-18074] Adding libfab Transport for all the STs
  conf/st
  configure.ac
  console/st/console-st.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  motr/st/m0d-fatal
  scripts/m0
  scripts/st.d/.gitignore
  spiel/st/m0t1fs_spiel_st.sh
  spiel/st/spiel_multiple_confd.sh
  sss/st
  st/m0mount-fail
  st/stob_domain_recreate_on_corruption.sh
  utils/functions
  utils/m0mount
  utils/spiel/m0spiel
Labels: cla-signed

#583 [DTM0] EOS-19130: Fix panic during disconnect.
  dtm0/service.c
  motr/conf.c
Labels: cla-signed

#567 EOS-19208: remove tx and segment dependency from btree code for benchmark.
  motr/m0crate/Makefile.sub
  motr/m0crate/btree_without_tx_seg.c
Labels: cla-signed

#587 EOS-18065 : Single node cluster on VM using libfabric transport
  net/bulk_emulation/mem_xprt_pvt.h
  net/bulk_emulation/ut/bulk_mem_ut.c
  net/libfab/libfab.c
Labels: cla-signed, libfabric_integration

#595 [DTM0] Do not release cs_params at the wrong moment.
  conf/objs/service.c
  dtm0/service.c
Labels: cla-signed

#603 doc: restored lnet transport pictures
  doc/Images/LNET.PNG
  doc/Images/LNET1.PNG
  doc/Images/revised.PNG
  doc/Motr_LNet_Transport.rst
  doc/PDF/HLD_Motr_LNet_Transport.pdf
Labels: cla-signed

#586 Update Quick-Start-Guide.rst
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#592 Fixes issue found in "fom-ub" by providing process_fid.
  fop/ub/ub.c
  lib/ub.c
Labels: cla-signed

#608 For custom build
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed

#600 client: improve code style of loops by iomaps
  m0t1fs/linux_kernel/file.c
  m0t1fs/linux_kernel/ut/file.c
  motr/client_internal.h
  motr/io_nw_xfer.c
  motr/io_pargrp.c
  motr/io_req.c
  motr/io_req_fop.c
Labels: cla-signed

#596 pool: improve struct m0_pool_version doc
  pool/pool.h
Labels: cla-signed

#614 EOS 19689 : Fix panic in ST 41
  net/test/st/st.sh
  rm/st/rwlock_helper.c
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
  scripts/m0
  spiel/st/m0t1fs_spiel_st.sh
Labels: cla-signed
