Repository Seagate/cortx-motr, pull requests merged in 2021-08, with the labels that each got.

#894 Eos 16852 : Support OVERWRITE record value in new bTree when new value size is same as value size of existing record.
  btree/btree.c
  btree/btree.h
  sm/op.c
Labels: cla-signed

#887 [EOS-22988] m0kv -help throwing ERROR in normal run
  lib/user_space/ugetopts.c
  motr/m0kv/cmd_main.c
Labels: cla-signed, needs-attention

#900 EOS-21940 Fix m0reportbug to work on devvm
  utils/m0reportbug
Labels: cla-signed

#891 EOS-20281 : Fix UTs and STs for seg_size=1Mb and seg_nr=1
  cas/ut/client_ut.c
  ioservice/ut/bulkio_common.c
  ioservice/ut/bulkio_common.h
  ioservice/ut/bulkio_ut.c
  iscservice/ut/service_ut.c
  layout/ut/plan.c
  motr/io_nw_xfer.c
  net/ut/buffer_pool_ut.c
  rpc/bulk.c
  rpc/ut/at/at_ut.c
  rpc/ut/at/at_ut.h
  sns/cm/repair/ut/net.c
  spiel/ut/spiel_conf_ut.c
Labels: cla-signed, libfabric_integration

#895 EOS-22075: Segregate tree_*() from ff_*() and mem_*()
  btree/btree.c
Labels: cla-signed

#911 EOS-22449: Make Intel ISA mandatory (No fallback)
  Makefile.am
  configure.ac
  cortx-motr.spec.in
  scripts/install-build-deps
Labels: cla-signed, isal_integration

#896 EOS-22555: Callback invokation on transaction commit.
  be/tx.c
  be/ut/main.c
  be/ut/tx.c
Labels: cla-signed

#903 EOS-23246: Min/Max key get implementation.
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#905 Eos 23143 : Credit calculation for KV UPDATE
  btree/btree.c
Labels: cla-signed

#902 EOS-20291: Removed kernel dependencies for UT's and ST's for libfabric transport
  conf/st
  console/st/console-st.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  motr/st/m0d-fatal
  motr/st/utils/motr_local_conf.sh
  net/test/st/st.sh
  net/test/test-user.sh.in
  scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
  scripts/install/usr/libexec/cortx-motr/motr-kernel
  spiel/st/spiel_multiple_confd.sh
  st/stob_domain_recreate_on_corruption.sh
  utils/functions
  utils/m0run
  utils/m0singlenode
Labels: cla-signed, libfabric_integration

#904 EOS-20759: Reset (Data and logs) phase of motr mini provisioner
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#888 EOS-23040: Add M0_ENF_META flag to identify metadata store
  motr/idx.c
  motr/idx_dix.c
  motr/obj.c
Labels: cla-signed

#918 Revert "[EOS-22988] m0kv -help throwing ERROR in normal run"
  lib/user_space/ugetopts.c
  motr/m0kv/cmd_main.c
Labels: cla-signed

#846 FDMI sample app
  Makefile.am
  fdmi/plugins/.gitignore
  fdmi/plugins/Makefile.sub
  fdmi/plugins/debug.c
  fdmi/plugins/fdmi_app
  fdmi/plugins/fdmi_sample_plugin.c
  utils/.gitignore
Labels: cla-signed

#912 EOS-23180: motr panic while bootstrapping cluster
  motr/setup.c
Labels: cla-signed

#884 EOS-22959: Fixed memory leak in degraded read path
  motr/client_internal.h
  motr/io_pargrp.c
Labels: cla-signed

#919 Decremented the loop count for ut multi_thread_tree_op
  btree/btree.c
Labels: cla-signed

#917 Return error codes instead of record's error flags in get and iter tick.
  btree/btree.c
Labels: cla-signed

#920 Adding interfaces for credits calculation for KV operation
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#921 EOS-22606: Credit Calculation for tree_create and tree_destroy
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#924 EOS-23337: Fix BE segment NULL-ptr'ed case within DTM0 log test
  be/ut/dtm0_log_ut.c
Labels: cla-signed

#922 Return code changes
  btree/btree.c
Labels: cla-signed

#857 isc: add demo library and app
  Makefile.am
  cortx-motr.spec.in
  iscservice/demo/.gitignore
  iscservice/demo/Makefile.sub
  iscservice/demo/README.rst
  iscservice/demo/common.c
  iscservice/demo/common.h
  iscservice/demo/iscdemo.c
  iscservice/demo/libdemo.c
  iscservice/demo/libdemo.h
  iscservice/demo/reglib.c
  iscservice/demo/util.c
  iscservice/demo/util.h
  iscservice/isc.c
  iscservice/isc.h
  lib/list.h
  utils/.gitignore
  xcode/proto
Labels: cla-signed

#892 EOS-19064:update motr_hare_keys for all nodes
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#934 Eos 19064 command without exception
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#932 EOS-23370 UT dix-client-ut failed
  motr/setup.c
Labels: cla-signed

#929 EOS-6616 net/sock: Nicely shutdown poller() thread in net/sock
  net/sock/sock.c
Labels: cla-signed

#930 EOS-22533 : Credits for delete operation
  btree/btree.c
Labels: cla-signed

#897 EOS-21983: m0reportbug binaries archive is missing on Jenkins
  utils/m0reportbug
Labels: cla-signed

#925 EOS-23038 - Ensure rc is initialized before conditional check.
  cas/client.c
Labels: cla-signed

#923 EOS-22492: Support bundle: Provide support.yaml to Foundation team
  Makefile.am
  scripts/install/opt/seagate/cortx/motr/conf/support.yaml
Labels: cla-signed

#931 FDMI plugin ST
  fdmi/plugins/fdmi_plugin_st.sh
  fdmi/plugins/fdmi_sample_plugin.c
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
Labels: cla-signed

#933 utils: fix help example in m0spiel
  utils/spiel/m0spiel
Labels: cla-signed

#936 EOS-22698: Design for variable sized key and value
  btree/btree.c
Labels: cla-signed

#939 Adding node interfaces for credit calculation for kv_operation
  btree/btree.c
Labels: cla-signed

#949 layout: fix comments at m0_layout_plan_build()
  layout/plan.c
Labels: cla-signed

#951 Return ENOENT error code if key not found in btree get operation.
  btree/btree.c
Labels: cla-signed

#952 Ut changes to test del rec validity
  btree/btree.c
Labels: cla-signed

#946 Eos 23372 : Design for Fix Key size, Variable Value size node type
  btree/btree.c
Labels: cla-signed

#938 No need to add extra ref after fdmi record is already processed.
  fdmi/plugin_dock.c
  fdmi/plugin_dock_fom.c
  fdmi/plugins/fdmi_sample_plugin.c
Labels: cla-signed

#953 EOS-23505_Added delay and retry in lvm fetch
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#943 EOS-10319 - Out of memory for m0crate
  motr/cob.c
  motr/m0crate/crate_io.c
  motr/m0crate/parser.c
Labels: cla-signed

#958 Update auto assign for the gatekeepers
  .github/auto_assign.yml
Labels: cla-signed

#959 Update CODEOWNERS
  CODEOWNERS
Labels: cla-signed

#947 doc: add isc/demo link to motr-developer-guide.md
  doc/motr-developer-guide.md
Labels: cla-signed

#948 lib: add m0_bitmap_ffs()
  lib/bitmap.c
  lib/bitmap.h
  lib/ut/bitmap.c
Labels: cla-signed

#963 Changes to credit calculation functions to include callback calculations
  be/tx_credit.c
  btree/btree.c
Labels: cla-signed

#965 Update CODEOWNERS
  CODEOWNERS
Labels: cla-signed

#960 EOS-23582: update the format of support.yaml file
  scripts/install/opt/seagate/cortx/motr/conf/support.yaml
Labels: cla-signed

#941 EOS-20759: Motr Mini Provisioner Cleanup implementation
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#833 lib: fix panic at m0_locality_chores_run() on NUMA nodes
  lib/linux_kernel/kthread.c
  lib/locality.c
  lib/thread.c
  lib/thread.h
  lib/user_space/uthread.c
Labels: cla-signed

#928 EOS-23124: Improve Troubleshooting section in Quick-Start-Guide
  doc/Quick-Start-Guide.rst
  scripts/install-build-deps
Labels: cla-signed

#962 EOS-22704: Re-Analyze small objects Read throughput with MD cache patch
  motr/idx.c
Labels: cla-signed

#969 Add global lock in tx commit callback
  btree/btree.c
Labels: cla-signed

#972 Fix for btree ut crash.
  btree/btree.c
Labels: cla-signed

#970 lib: fix bogus warnings about thread migration
  fop/fom.c
  fop/fom.h
  lib/locality.c
  lib/locality.h
  lib/thread.c
  lib/thread.h
Labels: cla-signed

#967 UT for Variable Key size, Variable Value size.
  btree/btree.c
Labels: cla-signed

#978 UTs for Fixed Key size, Variable Value size node format.
  btree/btree.c
Labels: cla-signed

#986 Changes to m0_btree_create() to deermine node type from m0_btree_type data
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#987 Updated btree.h with prototype of m0_btree_update() routine.
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#985 Btree ut validate persistence across cluster restarts
  btree/btree.c
Labels: cla-signed

#991 EOS-21986, EOS-22543: Added design details about libfabric transport implementation
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#990 EOS 23470 : Analysis of timeouts during S3 IOs and performance optimization
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#968 EOS-22444: Remove use of galois kernel module
  conf/st
  console/st/console-st.sh
  m0t1fs/linux_kernel/st/common.sh.in
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  net/lnet/st/linux_kernel/m0lnetping.sh
  net/test/demo/demo-test-run.sh
  net/test/m0nettest.sh.in
  net/test/m0nettestd.sh.in
  net/test/st/st.sh
  net/test/test-user.sh.in
  net/test/test.sh
  scripts/addb-py/chronometry/io_workload
  scripts/addb-py/chronometry/run_corruption_task
  scripts/addb-py/chronometry/run_s3_corruption
  scripts/addb-py/chronometry/run_s3_task
  scripts/addb-py/chronometry/run_task
  scripts/addb-py/chronometry/s3_corruption_workload
  scripts/addb-py/chronometry/s3_workload
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
  sns/cm/st/repair_test.sh
  spiel/st/m0t1fs_spiel_st.sh
  ut/m0kut
  utils/functions
  utils/m0mount
  utils/m0reportbug
  utils/m0run
  utils/modload-all.sh.in
Labels: cla-signed, isal_integration

#885 F23B: Detect data corruption: detect data corruption by validating checksum
  Makefile.am
  be/extmap.c
  be/extmap.h
  be/extmap_internal.h
  be/ut/extmap.c
  configure.ac
  cortx-motr.spec.in
  ioservice/io_foms.c
  ioservice/io_fops.c
  ioservice/io_fops.h
  lib/Kbuild.sub
  lib/Makefile.sub
  lib/cksum.c
  lib/cksum.h
  lib/cksum_utils.c
  lib/cksum_utils.h
  lib/misc.h
  motr/client.c
  motr/client.h
  motr/client_internal.h
  motr/composite_layout.c
  motr/io.c
  motr/io.h
  motr/io_nw_xfer.c
  motr/io_pargrp.c
  motr/io_req.c
  motr/io_req_fop.c
  motr/m0crate/crate_io.c
  motr/motr-pub.api
  motr/pg.h
  motr/st/cancel.c
  motr/st/layout.c
  motr/st/osync.c
  motr/st/read.c
  motr/st/utils/helper.c
  motr/st/write.c
  motr/ut/Makefile.sub
  motr/ut/client.h
  motr/ut/io_dummy.c
  motr/ut/io_nw_xfer.c
  motr/ut/io_req.c
  motr/ut/protection_info_checks.c
  rm/st/rwlock_helper.c
  scripts/beck/st/README
  scripts/beck/st/error_injection.py
  scripts/provisioning/roles/motr-build/vars/RedHat.yml
  scripts/provisioning/roles/motr-runtime/vars/RedHat.yml
  stob/ad.c
  stob/ad.h
  stob/io.h
  stob/ut/ad.c
  stob/ut/adieu.c
  ut/m0ut.c
Labels: cla-signed

#869 EOS-23898 : motr-freespace-monitor: Add a delay between retry if capacity_info is 0
  scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
Labels: cla-signed

#992 EOS-20508: Validate support bundle for Motr components
  scripts/install/opt/seagate/cortx/motr/conf/support.yaml
Labels: cla-signed

#914 "EOS-21909: unit test updates for balloc tunables."
  balloc/ut/balloc.c
Labels: cla-signed

#984 Fix "possible uninitialised" warnings.
  net/bulk_emulation/mem_xprt_bulk.c
  net/bulk_emulation/mem_xprt_ep.c
Labels: cla-signed

#976 Change in Alex workflow
  .github/workflows/alex_reviewdog.yml
Labels: cla-signed

#1011 Removed #ifndef __KERNEL__ wherever possible from btree.c file.
  btree/btree.c
Labels: cla-signed

#1013 Miscellaneous changes.
  be/alloc.h
  btree/btree.c
  btree/internal.h
Labels: cla-signed

#1015 UT for btree cursor verification.
  btree/btree.c
Labels: cla-signed

#1014 Eos 16853 : Implementation of Update Operation with variable value size
  btree/btree.c
Labels: cla-signed
