Repository Seagate/cortx-motr, pull requests merged in 2021-01, with the labels that each got.

#318 EOS-14948 Libfabric : Implement transfer machine start and stop using libfabric APIs
  net/libfab/libfab.c
Labels: cla-signed

#314 EOS-14949 Libfabric: Added buf_del() API and poller thread
  motr/magic.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed

#306 EOS-13057 ha: wait time added in ham utility for listening mode
  ha/ham-st
  ha/ham.c
Labels: cla-signed

#281 EOS-15132: reset bac_found for each block allocation criteria
  balloc/balloc.c
Labels: cla-signed

#179 EOS-11786 Enable DIX repair ST
  .xperior/testds/motr-single_tests.yaml
  cas/client.c
  cm/ag.c
  cm/ag.h
  cm/ag_store.c
  cm/cm.c
  cm/proxy.c
  cm/proxy.h
  cm/pump.c
  cm/repreb/sw_onwire_fom.c
  cm/repreb/sw_onwire_fop.c
  cm/sw.c
  cm/sw_update_fom.c
  conf/diter.c
  dix/cm/ag.c
  dix/cm/cm.c
  dix/cm/cm.h
  dix/cm/iter.c
  dix/cm/service.c
  dix/cm/st/dix_repair_st.sh
  dix/cm/st/src_vals.txt
  dix/req.c
  fop/fom.c
  fop/fom.h
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  motr/idx.c
  motr/idx_dix.c
  motr/magic.h
  rpc/rpc.c
  sns/cm/service.c
Labels: cla-signed

#310 Install Intel ISA-L from source and NASM from rpm
  scripts/install-build-deps
  scripts/provisioning/roles/base-os/tasks/main.yml
  scripts/provisioning/roles/motr-build/tasks/main.yml
  scripts/provisioning/roles/motr-build/vars/RedHat.yml
Labels: cla-signed

#317 EOS-15121 hold tb_lock before checking and put.
  be/queue.c
  be/tx_bulk.c
  be/ut/tx_bulk.c
Labels: cla-signed

#319 Adjust some programs installation destination.
  Makefile.am
Labels: cla-signed

#307 EOS 15847, EOS 14947 Libfabric : Rewrite domain init. Implement Transfer machine init and fini using libfabric API's.
  motr/init.c
  motr/magic.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#330 EOS-16485: support zero-spare configuration in DIX
  configure.ac
  dix/req.c
  dix/ut/client_ut.c
Labels: cla-signed

#324 go/mio: fix maxBs calc at getOptimalBlockSz()
  bindings/go/mio/mio.go
Labels: cla-signed

#344 build: bump version number to 1.0.1
  configure.ac
Labels: cla-signed

#62 EOS-10183: Add logging to m0_be_recovery_run()
  be/recovery.c
Labels: cla-signed

#241 EOS-14409 be/tool/beck: provide option to resume scan
  be/tool/beck.c
  scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Labels: cla-signed

#332 go/mcp: add check for already existing object
  bindings/go/mcp/mcp.go
  bindings/go/mio/mio.go
Labels: cla-signed

#335 go/mio: add io.Seeker interface
  bindings/go/mio/mio.go
Labels: cla-signed

#338 go/mio: add io.ReadAt() / io.WriteAt() implementations
  bindings/go/mio/mio.go
Labels: cla-signed

#350 EOS 14564 [Independent Network Transport] to libfab integration
  dix/utils/m0dixinit.c
  net/bulk_emulation/mem_xprt_xo.c
  net/bulk_emulation/st/main.c
  net/bulk_emulation/st/ping.h
  net/bulk_mem.h
  net/domain.c
  net/libfab/libfab.c
  net/lnet/lnet.h
  net/lnet/lnet_main.c
  net/lnet/lnet_xo.c
  net/lnet/st/ping.h
  net/module.c
  net/net.h
  net/sock/sock.c
  net/ut/bulk_if.c
  rpc/rpc.c
  rpc/rpc_machine.c
  rpc/ub/ub.c
Labels: cla-signed, libfabric_integration

#345 go/mio: fix getting the composite objs layout id
  bindings/go/mio/mio.go
Labels: cla-signed

#346 hsm: fix memleak at composite_io_divide()
  motr/composite_layout.c
Labels: cla-signed

#347 hsm: fix error handling at m0hsm_create()
  hsm/m0hsm_api.c
Labels: cla-signed

#348 go/mio: fix multi-threads i/o on composite objects
  bindings/go/mio/mio.go
Labels: cla-signed

#355 EOS-16638 Libfabric : Fix network-bulk ut using libfabric
  motr/magic.h
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed

#361 go/README: update mio -> go/mio
  bindings/go/README.md
Labels: cla-signed

#325 Added time-window parameters for m0addb2dump utility.
  addb2/dump.c
Labels: cla-signed, needs-attention

#351 EOS-16458 [DTM0] DTM0 LOG DLD
  be/dtm0_log.h
Labels: cla-signed

#341 README: fix portability information
  README.rst
Labels: cla-signed

#327 EOS-16420: [DTM0] Introduce clock source.
  dtm0/Kbuild.sub
  dtm0/Makefile.sub
  dtm0/clk_src.c
  dtm0/clk_src.h
  dtm0/ut/Makefile.sub
  dtm0/ut/clk_src_ut.c
  ut/m0ut.c
Labels: cla-signed

#352 EOS-16421: [DTM0] Add client SM DLD.
  dtm0/doc/dtx.txt
Labels: cla-signed

#358 mcp: add -off offset option
  bindings/go/README.md
  bindings/go/mcp/mcp.go
Labels: cla-signed

#359 hsm: fix write at offset on older extent
  motr/composite_layout.c
Labels: cla-signed

#326 provisioner: motr provisioning for single node
  Makefile.am
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
  scripts/install/opt/seagate/cortx/motr/conf/examples/motr_prov_conf.json
Labels: cla-signed

#363 Removing unused code.
  dix/cm/cm.c
  dix/req.c
Labels: cla-signed

#365 EOS-16866: [DTM0] Introduce tx_desc.
  dtm0/Kbuild.sub
  dtm0/Makefile.sub
  dtm0/clk_src.h
  dtm0/tx_desc.c
  dtm0/tx_desc.h
Labels: cla-signed

#368 EOS-16459: [DTM0] Updated log header to cleanup common structure
  be/dtm0_log.h
Labels: cla-signed

#369 provisioner: setup.yaml updated with new provisioner format
  scripts/install/opt/seagate/cortx/motr/conf/setup.yaml
Labels: cla-signed

#366 Update the Tested By section in the Quick-Start-Guide.rst
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#370 provisioning/README: add single-node example
  scripts/provisioning/README.md
  scripts/provisioning/build-prep-1node.sh
Labels: cla-signed
