Repository Seagate/cortx-motr, pull requests merged in 2022-06, with the labels that each got.

#1843 CORTX-30753: Codacy code cleanup(#1608)
  addb2/st/addb2dump-plugin.sh
  console/st/console-st.sh
  dix/cm/st/m0t1fs_dix_repair.sh
  fdmi/st/echo/echo_plugin_start.sh
  fdmi/st/fdmi_test.sh
Labels: cla-signed

#1851 CORTX-31960 : [Alex]Add set of words to exception list
  .alexrc
Labels: cla-signed

#1806 Codacy code cleanup
  doc/data-flow/conf.py
  doc/dev/conf.py
  scripts/addb-py/chronometry/fom_req.py
  scripts/addb-py/chronometry/hist.py
  scripts/addb-py/chronometry/io_req.py
  scripts/addb-py/chronometry/md_req.py
  scripts/addb-py/chronometry/queues.py
  scripts/addb-py/chronometry/s3server_integration/s3_overrides.py
  scripts/addb-py/chronometry/task_queue/config.py
  scripts/addb-py/filter.py
  scripts/addb2/addb2grammar.py
Labels: cla-signed

#1776 Codacy code cleanup
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#1834 Fix "Invalid entity fid detected" issue when boundary condition obj_id is passed …
  motr/examples/example1.c
Labels: cla-signed

#1735 CORTX-30751: Codacy code cleanup (#1606)
  m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh
Labels: WIP, cla-signed, rose, Status: Draft

#789 EOS-14840: Fix motr process panic in queueit() during shutdown
  fop/fom.c
  reqh/reqh_service.c
  reqh/reqh_service.h
Labels: WIP, cla-signed, rose, Status: Changes requested

#1624 CORTX-28519 : Inconsiderate words reported by Alex.
  doc/data-flow/s3-0.txt
  doc/manpages.md
  doc/motr-in-prose.md
  doc/outdated/AR_RPC_Layer.md
  doc/outdated/Build-Environment.md
  doc/outdated/Containers.md
Labels: cla-signed, rose, Status: Changes requested

#1820 CORTX-30993 - BE: Avoid usage of gft_tmp_op to put group fom op into active state
  be/tx_group_format.c
  be/tx_group_format.h
Labels: cla-signed, rose, Status: Waiting to be merged

#1862 Fix assertion during shutdown in m0_pools_service_ctx_destroy.
  pool/pool.c
Labels: cla-signed

#1839 update contributors number related with cortx-motr
  README.md
Labels: cla-signed, Status: Waiting to be merged

#1864 First phase changes adding support for usermode systemctl
  motr/st/utils/be_log_resize.sh
  scripts/addb-py/chronometry/corruption_workload
  scripts/addb-py/chronometry/io_workload
  scripts/addb-py/chronometry/p0
  scripts/addb-py/chronometry/p0_hare
  scripts/addb-py/chronometry/s3_corruption_workload
  scripts/addb-py/chronometry/s3_workload
  scripts/install/etc/sysconfig/motr
  scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh
  scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
  scripts/install/usr/lib/systemd/system/m0d@.service
  scripts/install/usr/lib/systemd/system/motr-mkfs.service
  scripts/install/usr/lib/systemd/system/motr-mkfs@.service
  scripts/install/usr/lib/systemd/system/motr-server-confd.service
  scripts/install/usr/lib/systemd/system/motr-server-ha.service
  scripts/install/usr/lib/systemd/system/motr-server@.service
  scripts/install/usr/lib/systemd/system/motr-trace@.service
  scripts/install/usr/lib/systemd/system/motr.service
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
  scripts/install/usr/libexec/cortx-motr/motr-trace
Labels: cla-signed

#1860 CORTX-32080: Codeowner Added
  CODEOWNERS
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1744 motr/setup: Send process RECOVERED event
  dtm0/domain.c
  dtm0/domain.h
  dtm0/it/boot/cdf.yaml
  dtm0/it/boot/env
  dtm0/it/boot/expected_kv_get_recurse_processes
  dtm0/it/boot/functions
  dtm0/it/boot/run
  motr/client_init.c
  motr/setup.c
Labels: cla-signed, rose, DTM0, Status: Waiting to be merged

#1814 CORTX-32108: Convert Motr HLD documents from .rst to .md format
  doc/HLD-Background-Scrub.md
  doc/HLD-Capability-Motr.md
  doc/HLD-Configuration-Schema.md
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1829 CORTX-30955 : Fix M0_PRE check for errcode parameter in m0_be_io_err_send
  be/ha.c
Labels: cla-signed, rose, Status: Changes requested

#1853 Cortx-32012: Codacy warning/issues fixes cleanup (#1852)
  scripts/addb-py/record.py
  scripts/gdb/gdb-extensions.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1848 CORTX-31984: Codacy warning/issue fixes (#1606)
  doc/data-flow/conf.py
  doc/dev/conf.py
  scripts/addb-py/chronometry/addb2db.py
  scripts/addb-py/chronometry/hist.py
  scripts/addb-py/chronometry/req_utils.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1871 Check that conf is initialized before accessing it
  dtm0/domain.c
Labels: cla-signed

#1840 CORTX-29888: Upgrade mini-provisioner interface (config) for rolling …
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1881 ut: update io-req-ut:device_check() test
  motr/ut/io_req.c
Labels: cla-signed

#1880 dtm/recovery: Address code review comments.
  dtm0/drlink.c
  dtm0/fop.h
  dtm0/recovery.c
  dtm0/recovery.h
Labels: cla-signed

#1866 CORTX-31617: fix data recovering on degraded read
  lib/vec.c
  lib/vec.h
  motr/client.h
  motr/io.c
  motr/io_nw_xfer.c
  motr/io_pargrp.c
  motr/io_req.c
  motr/st/utils/helper.c
  rpc/frmops.c
Labels: cla-signed

#1874 CORTX-30435: Support to configure SKIP_LAYOUT and CROW for m0crate
  motr/m0crate/crate_client.h
  motr/m0crate/crate_index.c
  motr/m0crate/parser.c
  motr/st/utils/m0crate_st_workloads.yaml
Labels: cla-signed

#1856 CORTX-31844: Client crashes on too many failures (#1838)
  conf/pvers.c
  fd/fd.c
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1784 m0trace: fix typo in --level help
  utils/trace/m0trace
Labels: cla-signed, rose, Status: Waiting to be merged

#1890 dtm/recovery: Address code review comments (part 3).
  dtm0/drlink.c
  dtm0/recovery.c
  dtm0/recovery.h
Labels: cla-signed

#1756 fdmi: fix source dock fom wakeup race
  fdmi/source_dock_fom.c
  fdmi/source_dock_internal.h
Labels: bug, cla-signed, rose, Status: Waiting to be merged

#1882 CORTX-31180 dtm0/cas: fix sdev ID for incoming REDO messages
  cas/cas.h
  cas/service.c
  dix/fid_convert.c
  dix/fid_convert.h
  dtm0/fop.c
  motr/ut/idx_dix.c
Labels: cla-signed

#1897 dtm/recovery: Address code review comments (part 4).
  be/dtm0_log.c
Labels: cla-signed

#1865 Add seg header validation in bnode_get()
  btree/btree.c
Labels: cla-signed, needs-attention

#1919 CORTX-32188: Fix 42motr-utils and 45motr-rmw ST failures for New Btree
  be/extmap.c
  be/extmap_internal.h
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  scripts/install/etc/sysconfig/motr
Labels: cla-signed

#1918 CORTX-31985: Set MOTR_M0D_MIN_RPC_RECVQ_LEN to 64 for VM
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed, Exception

#1646 dtm/recovery: Introduce recovery machine
  addb2/dump.c
  be/dtm0_log.c
  be/dtm0_log.h
  be/ut/dtm0_log_ut.c
  cas/cas.h
  cas/service.c
  dix/fid_convert.c
  dix/fid_convert.h
  dix/req.c
  doc/dld/dld-index.c
  dtm0/Makefile.sub
  dtm0/addb2.h
  dtm0/drlink.c
  dtm0/dtx.c
  dtm0/dtx.h
  dtm0/fop.c
  dtm0/fop.h
  dtm0/it/all2all/.gitignore
  dtm0/it/all2all/all2all
  dtm0/it/all2all/cdf.yaml
  dtm0/linux_kernel/stubs.c
  dtm0/recovery.c
  dtm0/recovery.h
  dtm0/service.c
  dtm0/service.h
  dtm0/ut/drlink.c
  dtm0/ut/main.c
  lib/user_space/timer.c
  motr/idx_dix.c
  motr/m0kv/index.c
  motr/m0kv/index.h
  motr/m0kv/index_parser.c
  motr/magic.h
  motr/ut/idx_dix.c
  rpc/conn.c
  rpc/rpc_opcodes.h
  scripts/gdb/gdb-extensions
  utils/m0hagen
Labels: cla-signed, rose, DTM0, changes_requested, Status: Draft

#1916 cortx-30077 : Fix codacy issues
  lib/bitmap.c
  lib/ut/cookie.c
Labels: cla-signed

#1910 CORTX-30082 : Fix Codacy issues under "dix" directory
  dix/layout.c
  dix/meta.c
Labels: cla-signed

#1913 CORTX-32364: Codacy code cleanup (#1912)
  scripts/addb-py/filter.py
Labels: cla-signed

#1905 CORTX-32333: Revert "CORTX-30751: Codacy code cleanup (#1606) (#1730)"
  fdmi/plugins/fdmi_plugin_st.sh
Labels: cla-signed

#1749 Codacy code cleanup
  scripts/addb-py/chronometry/md_req.py
  scripts/addb-py/chronometry/task_queue/tasks.py
  scripts/addb-py/filter.py
  scripts/addb-py/main.py
  scripts/addb-py/record.py
Labels: cla-signed, rose, Status: Checks failed

#1915 CORTX-32365: Codacy code cleanup (#1914)
  scripts/addb-py/chronometry/task_queue/task_queue.py
Labels: cla-signed

#1903 CORTX-30750_Comment_Rebalance_abort_test_in_71spiel-sns-motr-repair
  motr/st/utils/spiel_sns_motr_repair.sh
Labels: cla-signed

#1929 CORTX-32368: Increase FQDN length to 255 characters in motr for kubernetes
  net/ip.h
Labels: cla-signed

#1930 CORTX-32086 net: fix for io bulk failure when multiple hostnames associated with same ip
  motr/io_req_fop.c
  net/libfab/libfab.c
  reqh/reqh_service.c
Labels: cla-signed

#1884 client: fix degraded write on cob create
  motr/io_req_fop.c
Labels: cla-signed

#1917 CORTX-31955 : Fixed codacy issue for redundant if condition and
  cm/ag.c
  cm/ag_store.c
  cm/proxy.c
  cm/ut/cm.c
Labels: cla-signed

#1809 CORTX-31531 tests: load motr kernel module when LNET transport is selected
  conf/st
  console/st/console-st.sh
  motr/st/m0d-fatal
  motr/st/utils/motr_cmd.sh
  motr/st/utils/motr_fs.sh
  motr/st/utils/motr_local_conf.sh
  motr/st/utils/motr_remote_conf.sh
  net/test/st/st.sh
  scripts/install/usr/libexec/cortx-motr/motr-kernel
  spiel/st/m0t1fs_spiel_st.sh
  spiel/st/spiel_multiple_confd.sh
  st/m0mount-fail
  st/stob_domain_recreate_on_corruption.sh
  utils/functions
  utils/m0run
Labels: cla-signed, rose, Status: Changes requested

#1911 Motr minor changes
  doc/motr-in-prose.md
  doc/source-structure.md
Labels: cla-signed

#1904 cortx-30080: replace strlen with strnlen to satisfy Codacy
  cob/ns_iter.c
Labels: cla-signed

#1876 CORTX-31291 Removal of gdb from cortx images
  cortx-motr.spec.in
Labels: cla-signed

#1902 CORTX-30079 - Fix Codacy issue in rpc directory
  rpc/at.c
  rpc/formation2.c
  rpc/it/linux_kernel/load.sh
  rpc/it/linux_kernel/rpcload.sh
  rpc/it/linux_kernel/unload.sh
  rpc/it/rpc_ping.c
  rpc/ub/plot.sh
  rpc/ub/ub.c
Labels: cla-signed

#1895 CORTX-30063_fix_codacy_issue
  sns/cm/cm.c
  sns/cm/file.c
  sns/cm/repair/acc_cp.c
  sns/cm/repair/ag.c
  sns/cm/repair/ut/cp_common.c
  sns/ut/parity_math_ut.c
Labels: cla-signed

#1946 CORTX-30543 : Change segaddr_header_isvalid() as a generic function
  btree/btree.c
Labels: cla-signed

#1933 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/m0t1fs_spiel_dix_repair.sh
Labels: cla-signed

#1931 CORTX-32426:Motr mini provisioner log file contain only recent start…
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1901 CORTX-30751: Codacy code cleanup (#1606)
  st/m0d-signal-test.sh
Labels: cla-signed

#1892 CORTX-30751: Codacy code cleanup (#1606)
  st/m0mt-singlenode.sh
Labels: cla-signed

#1934 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/m0t1fs_spiel_dix_repair_quiesce.sh
Labels: cla-signed

#1900 CORTX-30751: Codacy code cleanup (#1606)
  st/m0d-fsync-test.sh
Labels: cla-signed
