Repository Seagate/cortx-motr, pull requests merged in 2022-03, with the labels that each got.

#1470 motr/st: Enabled motr st's skipped due to m0t1fs requirement
  motr/st/utils/motr_dgmode_io_st.sh
  motr/st/utils/motr_rmw_st.sh
  motr/st/utils/motr_sync_replication_st.sh
  utils/functions
Labels: cla-signed

#1514 CORTX-27365 : btree-ut:lru_test is failing
  balloc/ut/balloc.c
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#1512 CORTX-25679: Fix SNS Repair STs
  .gitignore
  .xperior/testds/motr-single_tests.yaml
  motr/st/utils/sns_repair_motr_quiesce.sh
  motr/st/utils/sns_repair_motr_shutdown.sh
  scripts/st.d/68sns-repair-motr-shutdown
  scripts/st.d/68sns-repair-shutdown
  scripts/st.d/69sns-repair-motr-quiesce
  scripts/st.d/69sns-repair-quiesce
  utils/functions
Labels: cla-signed

#1522 Addressed PR comments.
  balloc/balloc.c
  balloc/balloc.h
  be/extmap_internal.h
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#1495 CORTX-28870: Adding the allowable list for Alex scan
  .alexrc
  .github/workflows/alex_reviewdog.yml
Labels: cla-signed

#1436 EOS-28455: script to create a single node cluster
  scripts/jenkins/motr-hare-1node-cluster.groovy
Labels: cla-signed

#1519 CORTX-28516 : Libfabric - Compatibility for v1.12
  net/libfab/libfab.c
  net/libfab/libfab_internal.h
Labels: cla-signed, libfabric_integration

#1531 Fixed description in code to resolve PR comments.
  btree/btree.c
Labels: cla-signed

#1532 Removal of stale member variables in struct node_op.
  btree/btree.c
Labels: cla-signed

#1541 CORTX-29117: "server-restart-nomkfs", cas-service ut is failing in new btree
  cas/ut/service_ut.c
Labels: cla-signed

#1543 CORTX-29039:Fix Motr STs.
  console/st/console-st.sh
  scripts/m0
  utils/functions
  utils/spiel/cleanup-on-quit.txt
Labels: cla-signed

#1530 CORTX-23743: Add logging for DIX repair tests
  dix/cm/st/dix_repair_st.sh
  dix/cm/st/m0t1fs_dix_repair.sh
  dix/cm/st/m0t1fs_dix_repair_quiesce.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_dix_common_inc.sh
  spiel/st/m0t1fs_spiel_dix_repair.sh
  spiel/st/m0t1fs_spiel_dix_repair_quiesce.sh
Labels: cla-signed

#1544 CORTX-29220: Changes in cas module to use ff node format
  be/tool/beck.c
  cas/ctg_store.c
  cas/ctg_store.h
Labels: cla-signed

#1525 CORTX-29207: Script to run code coverage via Jenkins
  scripts/jenkins/code-coverage.groovy
Labels: cla-signed

#1537 CORTX-29450: Fix compilation errors for code coverage
  be/domain.c
  motr/motr-pub.api
  scripts/coverage/gcov-gen-html
Labels: cla-signed

#1553 Cortx-29009: ENOBUFS and ENODATA are expected during SNS repair.
  cm/sw_update_fom.c
Labels: cla-signed

#1555 CORTX-29525: Ignore symbols specific to code coverage
  motr/motr-pub.api
Labels: cla-signed

#1515 [DTM0] CORTX-28932: Versioned ordinary catalogues
  be/tool/beck.c
  cas/cas.c
  cas/cas.h
  cas/client.c
  cas/client.h
  cas/ctg_store.c
  cas/ctg_store.h
  cas/service.c
  cas/ut/client_ut.c
  cas/ut/service_ut.c
  dtm0/clk_src.c
  dtm0/clk_src.h
Labels: cla-signed

#1554 CORTX-29251: Added the codeowners
  CODEOWNERS
Labels: cla-signed

#1540 Suppress excess errors in kubectl logs due to Btree
  be/extmap.c
  btree/btree.c
  cas/ctg_store.c
  cob/cob.c
Labels: cla-signed

#1548 CORTX-29247: Support in motr config to set the watermarks for memory limits
  btree/btree.c
  btree/btree.h
  motr/setup.c
  motr/setup.h
  scripts/install/etc/sysconfig/motr
  scripts/install/opt/seagate/cortx/motr/conf/motr.conf
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
Labels: cla-signed

#1559 CORTX-28221: Changes in cob to support upgrade by adding version field
  cob/cob.c
  cob/cob.h
Labels: cla-signed

#1546 CORTX-29280 : Implement slow remapping of nodes in LRU list to avoid possible thrashing for random IO accesses.
  btree/btree.c
  btree/btree.h
Labels: cla-signed

#1528 CORTX-28510: Include PID into ADDB domain name in m0add2dump utility
  addb2/dump.c
Labels: cla-signed

#1539 WIP : CORTX-29193 : Removed deprecated keys
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1538 CORTX-27752: Rotation of core dump files.
  Makefile.am
  scripts/install/opt/seagate/cortx/motr/libexec/core_logrotate.sh
  scripts/install/usr/libexec/cortx-motr/motr-monitor
Labels: cla-signed

#1549 Motr terminology upload
  Motr-Terminology-Guide.md
Labels: cla-signed

#1552 Add link to Maestro
  doc/motr-developer-guide.md
Labels: cla-signed

#1516 CORTX-29143: Disable all-to-all reqh_service_ctx connections for DTM0 services
  pool/pool.c
Labels: cla-signed, DTM0

#1458 EOS-28492: Handle SIGTERM signal for m0d process
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
  scripts/install/usr/libexec/cortx-motr/motr-start
Labels: cla-signed

#1572 cortx-29816: m0spiel: Fix error in displaying help
  utils/spiel/m0spiel
Labels: cla-signed

#1463 Adding End-to-end-Data-Integrity.md file
  doc/End-to-end-Data-Integrity.md
Labels: cla-signed

#1464 Adding FOPFOM-Programing-Guide.md file
  doc/FOPFOM-Programming-Guide.md
Labels: cla-signed

#1557 Motr fdmi app page update to add link to fdmi demo page
  doc/motr-in-prose.md
  fdmi/plugins/motr-fdmi-app.md
Labels: cla-signed
