Repository Seagate/cortx-motr, pull requests merged in 2022-09, with the labels that each got.

#2107 CORTX-33803: Run UT's Individually
  .xperior/testds/motr-single_tests.yaml
Labels: cla-signed

#2113 CORTX-33834: Fixed rpc/conn.c m0_rpc_conn_ha_timer_start() memory leak
  rpc/conn.c
Labels: cla-signed

#1759 m0_confc_init_wait(): initialise bob earlier
  conf/confc.c
  conf/confc.h
  conf/rconfc.c
  spiel/ut/spiel_conf_ut.c
Labels: bug, cla-signed, needs-attention, rose, Status: Waiting to be Reviewed

#2122 CORTX-32492: Fix mdservice-ut failure in 00userspace-tests for Motr PR jenkins
  mdservice/ut/mdstore.c
Labels: cla-signed

#2120 CORTX-34042 - Fix load_extents logic in balloc module.
  balloc/balloc.c
  balloc/balloc.h
Labels: cla-signed

#2019 CORTX-26280 : Replace M0_ERR with M0_RC in case of ENOENT.
  cas/client.c
Labels: cla-signed, needs-attention, Status: Waiting to be Reviewed

#996 EOS-24059: Added helpful debug info in m0reportbug
  utils/m0reportbug
Labels: cla-signed, needs-attention, rose, Status: Waiting to be Reviewed, Status: Checks failed

#2090 Update and rename Motr Design Document List
  doc/motr-design-doc-list.md
  doc/motr-design-doc-list.rst
Labels: cla-signed

#2124 Revert "Update and rename Motr Design Document List from .rst to .md …
  doc/motr-design-doc-list.md
  doc/motr-design-doc-list.rst
Labels: cla-signed

#2093 CORTX-33973: Enable 04initscripts ST for libfabric
  st/initscripts
  utils/functions
Labels: cla-signed

#2126 CORTX-34151 dtm0: add redo log only if dtm is enabled
  cas/service.c
Labels: cla-signed

#2129 CORTX-34154: motr logs are not in compressed format
  utils/m0reportbug
Labels: cla-signed, Exception

#2103 CORTX-30371 fis: enable FI on both motr clients and servers
  conf/helpers.c
  configure.ac
  fis/fi_command_fops.c
  fis/fi_service.h
  motr/client_init.c
  motr/setup.c
  rpc/item.c
Labels: cla-signed

#2132 CORTX-34165 : Disable libfab-ut if libfabric is not present.
  ut/m0ut.c
Labels: cla-signed

#2115 CORTX-33899 : Delayed Motr service start makes cortx-rgw container restart
  motr/client_init.c
Labels: cla-signed

#2135 CORTX-23733 - Improved links in developers guide (motr-developer-guide.md)
  doc/motr-developer-guide.md
Labels: cla-signed

#1921 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/m0t1fs_spiel_sns_repair.sh
Labels: cla-signed, codacy, Status: Waiting to be Reviewed

#1850 CORTX-30753: Codacy code cleanup(#1608)
  m0t1fs/linux_kernel/st/m0t1fs_cc_io_with_sns_repair.sh
  m0t1fs/linux_kernel/st/m0t1fs_client.sh
  m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh
  m0t1fs/linux_kernel/st/m0t1fs_failure_after_sns_repair_quiesce.sh
  m0t1fs/linux_kernel/st/m0t1fs_fsync_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_fwait_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_multi_clients.sh
  m0t1fs/linux_kernel/st/m0t1fs_pool_version_assignment.sh
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1739 CORTX-30751: Codacy code cleanup (#1606)
  m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
Labels: WIP, cla-signed, rose, Status: Draft

#2138 CORTX-26613 : Fix Codacy errors for net/libfab/libfab.c
  net/libfab/libfab.c
Labels: cla-signed

#2140 CORTX-33129: Enable 26motr-user-kernel-tests ST which is disabled for libfabric
  .xperior/testds/motr-single_tests.yaml
  motr/st/st.c
  motr/st/utils/motr_client_st.sh
  scripts/st.d/26motr-user-tests
  utils/functions
Labels: cla-signed

#2145 CORTX-34094 Enable 10pver-assign ST
  motr/st/utils/cat.c
  motr/st/utils/client.c
  motr/st/utils/helper.c
  motr/st/utils/helper.h
  motr/st/utils/motr_pver_assign_st.sh
  motr/st/utils/motr_st_inc.sh
  scripts/st.d/10pver-assign
  utils/functions
Labels: cla-signed

#2083 CORTX-31894: Modify persistant UT
  be/btree.c
Labels: cla-signed

#2146 Cortx 27973
  cm/cm.h
  sns/cm/cm.c
  sns/cm/cm.h
  sns/cm/dtrebalance/cm.c
  sns/cm/rebalance/cm.c
  sns/cm/repair/cm.c
Labels: cla-signed

#2075 CORTX-33917: Enable versioned CAS ops without DTM0
  cas/cas.h
  cas/ctg_store.c
  cas/ut/client_ut.c
  dix/req.c
  dix/req_internal.h
  dix/ut/client_ut.c
  dtm0/dtx.c
  dtm0/tx_desc.c
  motr/idx_dix.c
  motr/setup_dix.c
Labels: cla-signed
