Repository Seagate/cortx-motr, pull requests merged in 2022-02, with the labels that each got.

#1388 reqh: md device service type is not M0_CST_IOS
  reqh/reqh.c
Labels: cla-signed

#1428 spec: drop "any" suffix for user mode only motr rpm name
  cortx-motr.spec.in
  scripts/build-prep-1node-cortx-mgw.sh
  scripts/install-build-deps
Labels: cla-signed

#1409 EOS-24703-Enable_sns_systemTests_with_libfabric
  .xperior/testds/motr-single_tests.yaml
  motr/st/utils/sns_failure_after_repair_quiesce.sh
  motr/st/utils/sns_repair_quiesce.sh
  motr/st/utils/sns_repair_shutdown.sh
  scripts/st.d/68sns-repair-shutdown
  scripts/st.d/69sns-repair-quiesce
  scripts/st.d/70sns-failure-after-repair-quiesce
Labels: cla-signed

#1414 sysconfig/motr: improve perf params documentation
  scripts/install/etc/sysconfig/motr
Labels: cla-signed

#1433 Checked the Quick Start Guide steps with CentOS-7.9
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#1439 Revert "reqh: md device service type is not M0_CST_IOS"
  reqh/reqh.c
Labels: cla-signed

#1444 EOS-28430 btree: btree-ut hangs when code compiled without --enable-debug flag
  btree/btree.c
  lib/user_space/user_x86_64_atomic.h
Labels: cla-signed

#1413 Fix outdated link
  doc/reading-list.md
Labels: cla-signed

#1448 be: fix doc cosmetics for m0_be_emap_paste()
  be/extmap.c
  scripts/install/etc/sysconfig/motr
Labels: cla-signed

#1449 EOS-27820: Memory limit functionality crashing with lower watermarks.
  balloc/balloc.h
Labels: cla-signed

#1438 EOS-28457 : GITHUB ISSUE-Kernel module compilation fails with --enable-debug
  configure.ac
Labels: cla-signed

#1454 EOS-28494: Fix the MAX_KEY_SIZE issue for vkvv format
  btree/btree.c
Labels: cla-signed

#1453 EOS-27537 : Services for the pod which is restarted are going in offline state.
  net/libfab/libfab.c
Labels: cla-signed

#1465 EOS-27813: Updating the M0_ASSERT to M0_ASSERT_EX for expensive_invariant
  btree/btree.c
Labels: cla-signed

#1423 EOS-27040 cob: Implement new btree for bytecount table to store pool version information.
  be/btree.h
  cob/cob.c
  cob/cob.h
  cob/ut/Makefile.sub
  cob/ut/bytecount.c
  ut/m0ut.c
Labels: cla-signed

#1365 EOS-27028: Spiel APIs for retriving byte count and status of pool version
  conf/pvers.c
  conf/pvers.h
  motr/motr-pub.api
  spiel/cmd.c
  spiel/spiel.h
  spiel/ut/spiel_ci_ut.c
Labels: WIP, cla-signed

#1446 EOS-27039: Added spiel API to fetch bytecount from ioservice
  spiel/cmd.c
  spiel/spiel.h
  spiel/ut/spiel_ci_ut.c
  sss/process_foms.c
  sss/process_fops.c
  sss/process_fops.h
Labels: cla-signed

#1468 EOS-27572: Motr CI: failure seen in dix-client-ut while running local failures test
  dix/ut/client_ut.c
Labels: cla-signed

#1437 EOS-28441 : Convert a Wiki Page into a .rst or .md document
  doc/Running_Motr_Across_a_Cluster.md
Labels: cla-signed

#1394 Updated link in client.h overview
  motr/client.h
Labels: cla-signed

#1461 EOS-27591 BE tool to dump CAS tree
  Makefile.am
  cas/.gitignore
  cas/Makefile.sub
  cas/ctg_store.c
  cas/ctg_store.h
  cas/m0ctgdump.c
  utils/.gitignore
Labels: cla-signed

#1469 EOS-27717: Don't post FDMI records if no FDMI filters defined.
  fdmi/fol_fdmi_src.c
  fdmi/source_dock_fom.c
  fdmi/source_dock_internal.h
  fdmi/ut/fol_ut.c
Labels: cla-signed, needs-attention

#1491 EOS-28836: dix-client-ut:server-is-down with panic
  dix/ut/client_ut.c
Labels: cla-signed

#1492 reset src_dock->fsdc_filters_defined manually in the end of UT
  fdmi/ut/fol_ut.c
Labels: cla-signed

#1478 configure: fix --enable-debug for kernel module
  addb2/sys.c
  cas/client.c
  conf/cache.c
  conf/helpers.c
  configure.ac
  ha/link.c
  layout/linear_enum.c
  lib/locality.c
  motr/st/layout.c
  rm/rm_fops.c
  rpc/link.c
Labels: cla-signed

#1474 go: update module name to cortx-motr/bindings/go
  bindings/go/README.md
  bindings/go/go.mod
  bindings/go/mcp/mcp.go
  bindings/go/mkv/mkv.go
Labels: cla-signed, needs-attention

#1494 CORTX-27957: Add st for DIX repair using m0repair utility.
  .xperior/testds/motr-single_tests.yaml
  dix/cm/st/dix_repair_st.sh
  dix/cm/st/m0t1fs_dix_repair.sh
  dix/cm/st/m0t1fs_dix_repair_quiesce.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_dix_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh
  motr/st/utils/motr_st_inc.sh
  scripts/st.d/23dix-repair-m0repair
  scripts/st.d/23dix-repair-quiesce-m0repair
  scripts/st.d/24motr-dix-repair-lookup-insert-m0repair
  scripts/st.d/24motr-dix-repair-lookup-insert-spiel
  scripts/st.d/24motr-dix-repair-m0repair
  scripts/st.d/24motr-dix-repair-spiel
Labels: cla-signed

#1490 CORTX-27592 add a test script for m0ctgdump
  cas/ctg_store.c
  cas/m0ctgdump-howto.md
  cas/st/ctgdump_tesh.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
Labels: cla-signed

#1484 EOS-28602: Validate the UT for M0_OIF_SKIP_LAYOUT when enabled forcefully
  cas/client.c
  dix/req.c
  motr/idx_dix.c
  motr/ut/idx_dix.c
Labels: cla-signed

#1500 Fix compilation with --enable-debug on CentOS 7.9
  conf/cache.c
Labels: cla-signed

#1493 EOS-27044: Integrate bytecount btree operations in write and delete path
  ioservice/cob_foms.c
  ioservice/io_foms.c
  ioservice/io_service.h
Labels: cla-signed

#1498 EOS-28387: Added a bytecount btree operation to dump all key-values
  cob/cob.c
  cob/cob.h
  cob/ut/bytecount.c
Labels: cla-signed

#1477 EOS-25683: [F-53B]Optimize component bundle size - Motr.
  scripts/install/opt/seagate/cortx/motr/libexec/m0reportbug-bundler
Labels: cla-signed

#1450 scripts/install-build-deps: skip Powertools repo installation if exists
  scripts/install-build-deps
Labels: cla-signed

#1434 EOS-25603: return skip for skipped tests
  scripts/m0
  utils/functions
Labels: cla-signed
