Repository Seagate/cortx-motr, pull requests merged in 2022-05, with the labels that each got.

#1686 Fix crash of all ios processes in some write scenarios
  motr/io_req.c
  motr/st/utils/motr_utils_st.sh
  stob/ad.c
Labels: cla-signed

#1621 CORTX-30751: Codacy code cleanup (#1606)
  m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh
  m0t1fs/linux_kernel/st/m0t1fs_multi_clients.sh
  m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh
  motr/st/utils/motr_device_util.sh
  motr/st/utils/motr_dgmode_io_st.sh
Labels: cla-signed

#1627 global_philter(): fix inherently racy UT.
  addb2/ut/consumer.c
Labels: bug, cla-signed

#1636 Fixed codacy issue related to security and duplication
  scripts/beck/st/error_injection.py
Labels: cla-signed, needs-attention

#1643 Use unique pathnames to avoid clashes in randomised UT runs
  stob/ut/stob.c
Labels: cla-signed, needs-attention

#1649 Use unique stob domain names in UT-s.
  addb2/ut/storage.c
  conf/ut/load.c
  stob/ut/ad.c
  stob/ut/adieu.c
  stob/ut/stobio.c
Labels: cla-signed

#1653 motr/client: improve M0_IC_LIST op API doc
  be/dtm0_log.h
  motr/client.h
Labels: cla-signed

#1692 sns/cm/repair/ut: use different domain paths for ad and linux stobs.
  sns/cm/repair/ut/cp_common.c
Labels: cla-signed, needs-attention

#1694 detour_create(): fix unreliable UT.
  fdmi/ut/pd_ut.c
Labels: cla-signed, needs-attention

#1697 fdmi-filterc-ut:filterc-connect-to-confd: free resources after stoppi…
  fdmi/ut/filterc_ut.c
Labels: cla-signed, needs-attention

#1700 m0_addb2_sensor: move s_magic field.
  addb2/addb2.h
Labels: cla-signed, needs-attention

#1718 CORTX-28925: Append timestamp/any unique value to m0trace to
  lib/user_space/utrace.c
Labels: cla-signed

#1677 CORTX-30965 Add NODTM per-operation flag to MOTR client interface
  cas/cas.h
  cas/client.c
  cas/service.c
  dix/req.c
  motr/idx.c
  motr/idx.h
  motr/idx_dix.c
  motr/ut/idx_dix.c
Labels: cla-signed

#1723 CORTX-29418 : Add support for libfabric v1.14.x and v1.15.x
  net/libfab/libfab.c
Labels: cla-signed

#1743 CORTX-31248: Initialize m0_idx_op with zeroes in m0kv index_op.
  motr/m0kv/index_op.c
Labels: cla-signed

#1729 CORTX-30785: Fixing the Alex bug
  .github/workflows/alex_reviewdog.yml
Labels: cla-signed

#1726 client: fix corrupted read on 2+ drive fails
  motr/io_req.c
  motr/io_req_fop.c
Labels: cla-signed

#1683 CORTX-30964 : Fix matrix invert failure for different N,K
  sns/parity_math.c
Labels: cla-signed

#1724 CORTX-30550: Resolve btree pr review comments
  btree/btree.c
Labels: cla-signed

#1750 CORTX-31264: fix SNS system tests regression
  motr/io_req.c
Labels: cla-signed

#1669 client: do degraded read on a disk error right away
  m0t1fs/linux_kernel/file.c
  motr/io_req.c
Labels: cla-signed

#1701 client: return write success on <= K failures
  motr/io_nw_xfer.c
  motr/io_req.c
Labels: cla-signed

#1765 CORTX-31292: fix m0tr.ko build regression
  motr/io_req.c
Labels: cla-signed

#1740 go/mio: add optional connection params to Init()
  bindings/go/mio/mio.go
Labels: cla-signed

#1550 Test Motr application example to handle object.
  doc/motr-object-app.md
Labels: cla-signed

#1659 Fix a race between reqh service connection and shutdown
  reqh/reqh_service.c
Labels: bug, cla-signed, motr

#1689 m0_rpc_service_reverse_session_*(): cleanup
  rm/rm.c
  rpc/service.c
  rpc/service.h
Labels: bug, cla-signed

#1691 m0_net_ip_lnet_parse(): avoid clashes between wildcards and explicit …
  net/ip.c
Labels: bug, cla-signed

#1693 net_test_network_ctx_initfini(): do not wait on failed initialisation
  net/test/network.c
Labels: bug, cla-signed

#1695 Add gdb wrapper script ./scripts/gdb/gdbrc, which see for the explana…
  scripts/gdb/gdbrc
Labels: cla-signed

#1753 utils/m0run: add "user" debugger.
  utils/m0run
Labels: cla-signed

#1755 m0_dtm0_fop_fini(): finalise fop addb instrumentation
  dtm0/fop.c
Labels: bug, cla-signed

#1763 CORTX-28925-new: Append timestamp/any unique value to m0trace to
  lib/user_space/utrace.c
Labels: cla-signed

#1746 CORTX-31056: Fix 52motr-singlenode-sanity system test
  scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
  st/sanity.sh
  utils/functions
Labels: cla-signed

#1565 CORTX-29629: Enable options setting for creating builds
  scripts/jenkins/build
  scripts/jenkins/code-coverage-with-xperior-and-doxygen.groovy
Labels: cla-signed

#1752 m0_getopts(): check for duplicate options
  lib/user_space/ugetopts.c
Labels: bug, cla-signed

#1709 Updated README.md for adding all badges
  README.md
Labels: cla-signed

#1748 CORTX-30766: Adding Alex's exception list
  .alexrc
Labels: cla-signed

#1728 client: use no hole mode by default
  motr/client.h
  motr/io.c
  motr/io_nw_xfer.c
  motr/st/utils/cat.c
  motr/st/utils/helper.c
  motr/st/utils/motr_utils_st.sh
  motr/st/utils/truncate.c
Labels: cla-signed

#1751 cm-ut:cm_ag_ut: zero structures before use
  cm/ut/cm.c
Labels: bug, cla-signed

#1770 CORTX-30921: Add spiel support for dix repair and rebalance in m0_ha_sim
  scripts/install/opt/seagate/cortx/motr/common/m0_dix_utils_common.sh
  scripts/install/opt/seagate/cortx/motr/common/m0_sns_utils_common.sh
  scripts/install/opt/seagate/cortx/motr/common/m0_spiel_dix_utils_common.sh
  scripts/install/opt/seagate/cortx/motr/common/m0_utils_common.sh
  scripts/install/opt/seagate/cortx/motr/libexec/m0_ha_sim
  spiel/st/m0t1fs_spiel_dix_common_inc.sh
Labels: cla-signed

#1768 Improve code coverage for SNS rebalance
  sns/cm/repair/ut/cm.c
  ut/m0ut.c
Labels: cla-signed

#1720 CORTX-29834: Remove dependency from key storage, instead use cvg
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: WIP, cla-signed

#1769 remove ruby lib from motr repo
  Makefile.am
  cortx-motr.spec.in
  scripts/provisioning/roles/motr-runtime/vars/RedHat.yml
  utils/Makefile.sub
Labels: cla-signed

#1545 CORTX-27608 dix/dtm0: add support of transient failures for PUT
  be/dtm0_log.c
  be/dtm0_log.h
  dix/req.c
  dtm0/dtx.c
  dtm0/dtx.h
  dtm0/fop.c
  dtm0/tx_desc.c
  dtm0/tx_desc.h
Labels: cla-signed

#1777 CORTX-30920: Add m0spiel support in m0_ha_sim for SNS Rep/Reb.
  Makefile.am
  debian/cortx-motr.install
  scripts/install/opt/seagate/cortx/motr/common/m0_spiel_sns_utils_common.sh
  scripts/install/opt/seagate/cortx/motr/libexec/m0_ha_sim
Labels: cla-signed

#1778 adding fop/wire_xc.c to the kernel build.
  fop/Kbuild.sub
Labels: cla-signed

#1780 CORTX-29192: spiel sns repair ST failing at last step
  motr/st/utils/spiel_sns_motr_repair.sh
  spiel/st/m0t1fs_spiel_sns_common_inc.sh
Labels: cla-signed

#1679 Moving old .rst file to archives folder
  archives/AR_RPC_Layer.rst
  archives/Build_Environment.rst
  archives/CORTX_MOTR_ARCHITECTURE.rst
  archives/Castor_Management.rst
  archives/Containers.rst
  archives/DTM.rst
  archives/Data_Organization.rst
  archives/End-to-end_Data_Integrity.rst
  archives/FOPFOM_Programming_Guide.rst
  doc/Castor-Management.md
  doc/DTM.md
Labels: cla-signed

#1779 CORTX-31300: Memory leak in hax m0_ha_proc_counters_fetch API
  motr/motr-pub.api
  spiel/cmd.c
  spiel/spiel.h
Labels: cla-signed

#1795 CORTX-31497: Fix 52motr-singlenode-sanity system test for lnet transport
  scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
Labels: cla-signed

#1793 CORTX-29815 m0spiel: Add support for new address format
  spiel/st/spiel_multiple_confd.sh
  utils/functions
  utils/spiel/m0spiel
Labels: cla-signed

#1803 CORTX-30872 dix: add support of transient failures for GET
  dix/req.c
  dix/req_internal.h
Labels: cla-signed

#1790 Fix m0trace 'experimental' warnings on Rocky Linux
  utils/trace/m0trace
Labels: cla-signed

#1794 CORTX-31523: Support rpm creation with --enable-dtm0 flag
  configure.ac
  cortx-motr.spec.in
Labels: cla-signed

#1798 CORTX-30947: Codacy: Fix 'Division by Zero' issue
  lib/ut/fold.c
Labels: cla-signed

#1155 EOS-24484: Added DTM0 Log iterator and UTs.
  be/dtm0_log.c
  be/dtm0_log.h
  be/ut/dtm0_log_ut.c
  motr/ut/idx_dix.c
Labels: cla-signed, Status: Unresolved Conversations

#1818 Modifying README
  scripts/provisioning/README.md
Labels: cla-signed

#1830 rpc: ioservices fail to connect to each other on larger setups (15, 24)
  scripts/install/etc/sysconfig/motr
Labels: cla-signed

#1819 client: do degraded read when -ENOENT is returned
  motr/io_req.c
Labels: cla-signed

#1214 isc: add min/max for 8-byte double arrays demo
  iscservice/demo/iscdemo.c
  iscservice/demo/libdemo.c
Labels: WIP, cla-signed, rose, Status: Waiting to be merged

#1815 CORTX-31605 dix/ut: add UTs for degraded GET and NEXT (OFFLINE devs)
  dix/ut/client_ut.c
Labels: cla-signed

#1831 Revert "CORTX-30947: Codacy: Fix 'Division by Zero' issue"
  lib/ut/fold.c
Labels: cla-signed

#1837 CORTX-30751: Codacy code cleanup (#1606)
  m0t1fs/linux_kernel/st/m0t1fs_cc_io_with_sns_repair.sh
Labels: cla-signed

#1811 Cortx 31436 fix duplications iter ut
  dix/cm/ut/iter_ut.c
Labels: cla-signed

#1813 go/README: add links for Reader/Writer interface
  bindings/go/README.md
Labels: cla-signed

#1785 be/log_discard: sync again in sync completion ast during flush if needed
  be/log_discard.c
Labels: cla-signed
