Repository Seagate/cortx-motr, pull requests merged in 2022-08, with the labels that each got.

#2031 Undo the Revert of CORTX-33703 Codacy code cleanup (#2001)
  README.md
  bindings/go/README.md
  doc/ADDB.md
  doc/CORTX-MOTR-ARCHITECTURE.md
  doc/DTM.md
  doc/FDMI-High-Level-Decomposition.md
  doc/FOPFOM-Programming-Guide.md
  doc/Running_Motr_Across_a_Cluster.md
  doc/Seagate-FDMI-Design-Notes.md
  doc/Seagate-FDMI-HLD.md
  doc/coding-style.md
Labels: cla-signed, Exception

#2034 CORTX-33702: Codacy Cleanup : Warn when the spacing between a list item’s bullet and its content violates.
  doc/CORTX-MOTR-ARCHITECTURE.md
Labels: cla-signed, Exception

#2038 CORTX-33595: Motr should support separate log device for deployment
  scripts/install/usr/libexec/cortx-motr/motr-server
Labels: cla-signed

#2036 CORTX-33634: IO Failing after pod restart
  net/libfab/libfab.c
Labels: cla-signed

#2032 CORTX-33346: Codacy Code cleanup
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#2042 CORTX_30099: add new request handler for SNS Direct Rebalance
  rpc/rpc_opcodes.h
Labels: cla-signed

#2028 Uploading markdown files to doc folder
  doc/HLD-Data-Block-Allocator.md
  doc/HLD-OF-Motr-LNet-Transport.md
  doc/HLD-Version-Numbers.md
  doc/HLD-of-FDMI.md
  doc/HLD-of-FOL.md
  doc/HLD-of-Metadata-Backend.md
  doc/HLD-of-Motr-Caching.md
  doc/HLD-of-Motr-HA-nterface.md
  doc/HLD-of-Motr-Lostore.md
  doc/HLD-of-Motr-Network-Benchmark.md
  doc/HLD-of-Motr-Object-Index.md
  doc/HLD-of-Motr-Spiel-API.md
  doc/HLD-of-SNS-Repair.md
  doc/HLD-of-SNS-client.md
  doc/HLD-of-distributed-indexing.md
  doc/ISC-Service-User-Guide
  doc/ISC-Service-User-Guide.md
  doc/Motr-Epochs-HLD.md
  doc/Motr-Lnet-Transport.md
Labels: cla-signed, Exception

#2025 CORTX-33757: Move new btree code files to be directory
  Kbuild.in
  Makefile.am
  balloc/balloc.h
  be/Kbuild.sub
  be/Makefile.sub
  be/be.c
  be/be.h
  be/btree.c
  be/btree.h
  be/btree_internal.h
  be/extmap.h
  be/extmap_internal.h
  be/tool/beck.c
  btree/Kbuild.sub
  btree/Makefile.sub
  cas/ctg_store.h
  cas/service.c
  cob/cob.c
  cob/cob.h
  conf/db.c
  doc/sm/index.rst
  motr/init.c
  motr/m0crate/crate.c
Labels: cla-signed

#2027 CORTX-30751: Codacy code cleanup (#1606)
  net/test/st/run-1x1.sh
Labels: cla-signed

#2035 CORTX-33703- [Codacy code cleanup] occurrence: 862 pattern: Warn when the spacing between a list item’s bullet and its content violates.
  doc/ADDB_Monitoring.md
  doc/CORTX-MOTR-ARCHITECTURE.md
  doc/End-to-end-Data-Integrity.md
  doc/Seagate-FDMI-Design-Notes.md
  doc/outdated/Containers.md
  doc/trace.md
  doc/workarounds.md
  fdmi/plugins/motr-fdmi-app.md
  hsm/README.md
  scripts/provisioning/README.md
Labels: Exception

#2030 CORTX-33718: Disable 37protocol till release time
  .xperior/testds/motr-single_tests.yaml
  st/protocol
Labels: cla-signed

#2033 CORTX-30751: Codacy code cleanup (#1606)
  net/test/st/st-ping.sh
  rpc/ub/plot.sh
Labels: cla-signed

#1987 CORTX-32897: Support default parameters for pre-merge job
  scripts/install/usr/libexec/cortx-motr/motr-cleanup
  scripts/jenkins/motr-hare-1node-cluster.groovy
Labels: cla-signed

#2054 CORTX-33505: Add tree type in node header of btree node.
  be/btree.c
  doc/sm/index.rst
Labels: cla-signed

#2062 CORTX-29985: DTM integration test
  scripts/jenkins/dtm-integration.groovy
Labels: cla-signed, Exception

#2063 CORTX-33741 : Analyze and fix memory leaks for emap module using s3 IOs with valgrind.
  balloc/ut/balloc.c
  be/extmap.c
  stob/ad.c
Labels: cla-signed, Status: Waiting to be merged

#2064 CORTX-31907- panic at m0_balloc_load_extents()
  balloc/balloc.c
Labels: cla-signed, Status: Waiting to be merged

#2056 CORTX-33852: Fix codecy issues
  doc/HLD-of-SNS-Repair.md
Labels: cla-signed, codacy, Status: Waiting to be Reviewed, Exception

#2047 CORTX-33829: Remove m0iscorrupt and core-traces files
  Makefile.am
  debian/cortx-motr.install
  scripts/install/opt/seagate/cortx/motr/common/core-traces
  utils/Makefile.sub
  utils/m0iscorrupt
Labels: cla-signed, Status: Waiting to be merged

#2039 CORTX-33702: Codacy cleanup of markdown files
  doc/Castor-Management.md
  doc/FDMI-High-Level-Decomposition.md
  doc/FOPFOM-Programming-Guide.md
  doc/HLD-Meta-Data-Back-End.md
  doc/HLD-OF-Motr-LNet-Transport.md
  doc/HLD-Version-Numbers.md
  doc/HLD-fop-object-Iterator.md
  doc/HLD-of-Auxillary-Databases.md
  doc/HLD-of-FDMI.md
  doc/HLD-of-Metadata-Backend.md
  doc/HLD-of-Motr-Caching.md
  doc/HLD-of-Motr-HA-nterface.md
  doc/Motr-Epochs-HLD.md
  doc/Motr-Lnet-Transport.md
  doc/Seagate-FDMI-Design-Notes.md
  doc/Seagate-FDMI-HLD.md
  doc/coding-style.md
  doc/motr-in-prose.md
  doc/motr-kv-app.md
  doc/motr-object-app.md
Labels: cla-signed, codacy, Status: Waiting to be Reviewed

#1975 CORTX-31595 - Exclude CODE_OF_CONDUCT file from Alex Scan
  .alexignore
Labels: cla-signed, Status: Waiting to be Reviewed, Exception

#2055 CORTX-33703- codacy cleanup: Fixed codacy formatting issues
  2035.diff
  doc/ADDB_Monitoring.md
  doc/CORTX-MOTR-ARCHITECTURE.md
  doc/HLD-FOP-State-Machine.md
  doc/HLD-Resource-Management-Interface.md
  doc/HLD-of-Catalogue-Service.md
  doc/HLD-of-FOL.md
  doc/HLD-of-Motr-Lostore.md
  doc/HLD-of-Motr-Network-Benchmark.md
  doc/HLD-of-Motr-Object-Index.md
  doc/HLD-of-Motr-Spiel-API.md
  doc/ISC-Service-User-Guide.md
  doc/Running_Motr_Across_a_Cluster.md
  scripts/provisioning/README.md
Labels: cla-signed, codacy, Status: Waiting to be Reviewed, Exception

#2072 CORTX-33725: Add lock for m0_rpc_bulk buffer(rbulk)
  motr/io_req_fop.c
Labels: cla-signed

#2073 CORTX-33927: Deployment failure due to wrong traversing of consul conf store
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#2068 CORTX-30751: Codacy code cleanup (#1606)
  motr/st/utils/sns_repair_motr_shutdown.sh
  motr/st/utils/spiel_sns_motr_repair.sh
  motr/st/utils/spiel_sns_motr_repair_quiesce.sh
Labels: cla-signed

#1970 CORTX-33577: fix panic in degraded mode read
  motr/io_nw_xfer.c
Labels: cla-signed, Status: Changes requested

#1888 Handling 'short' write in some cases, e.g. disk full.
  .xperior/testds/motr-single_tests.yaml
  ioservice/io_foms.c
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  motr/st/utils/copy.c
  motr/st/utils/motr_io_small_disks.sh
  motr/st/utils/sns_repair_common_inc.sh
  scripts/st.d/73motr-io-small-disks
Labels: cla-signed, Status: Waiting to be Reviewed

#2067 CORTX-29965: Add support for invoking sns direct rebalance via spiel calls
  cm/repreb/cm.h
  cm/repreb/trigger_fom.c
  motr/motr-pub.api
  rpc/rpc_opcodes.h
  sns/cm/cm.h
  sns/cm/dtrebalance/trigger_fop.c
  sns/cm/trigger_fom.c
  sns/cm/trigger_fop.h
  sns/cm/trigger_fop_common.c
  spiel/cmd.c
  spiel/spiel.h
  spiel/ut/conf.cg
  spiel/ut/spiel_ci_ut.c
  ut/conf.cg
  utils/functions
Labels: cla-signed

#2077 Fix Codacy Badge
  README.md
Labels: cla-signed, Exception

#1875 CORTX-30378 : DI generation in motr for data and parity
  .xperior/testds/motr-single_tests.yaml
  be/extmap.c
  be/extmap_internal.h
  be/ut/extmap.c
  debian/cortx-motr-dev.install
  ioservice/io_foms.c
  ioservice/io_fops.h
  layout/layout.c
  layout/layout_pver.c
  lib/Makefile.sub
  lib/cksum.c
  lib/cksum.h
  lib/cksum_data.h
  lib/cksum_utils.c
  lib/cksum_utils.h
  motr/client.h
  motr/client_internal.h
  motr/composite_layout.c
  motr/io.c
  motr/io.h
  motr/io_nw_xfer.c
  motr/io_req.c
  motr/io_req_fop.c
  motr/m0crate/crate_io.c
  motr/pg.h
  motr/st/utils/cat.c
  motr/st/utils/cc_cp_cat.c
  motr/st/utils/client.c
  motr/st/utils/copy.c
  motr/st/utils/copy_mt.c
  motr/st/utils/helper.c
  motr/st/utils/helper.h
  motr/st/utils/motr_di_corruption_detection_st.sh
  motr/st/utils/motr_rmw_st.sh
  motr/st/utils/motr_rpc_cancel_test.sh
  motr/st/utils/motr_st_inc.sh
  motr/st/utils/motr_sync_replication_st.sh
  motr/st/utils/motr_utils_st.sh
  motr/ut/io_dummy.c
  motr/ut/io_nw_xfer.c
  motr/ut/io_req.c
  motr/ut/protection_info_checks.c
  scripts/beck/st/error_injection.py
  scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
  scripts/st.d/73motr-di-corruption-detection
  scripts/st.d/74motr-di-corruption-detection
  stob/ad.c
  stob/io.h
  stob/ut/ad.c
  stob/ut/adieu.c
Labels: Status: Changes requested

#2070 Move documentation to main branch
  doc/CORTX-MOTR-ARCHITECTURE.md
  doc/pdclust/RAID.drawio
  doc/pdclust/RAID.png
  doc/pdclust/index.rst
  doc/pdclust/layout-rr-affected.drawio
  doc/pdclust/layout-rr-affected.png
  doc/pdclust/layout-rr-failure.drawio
  doc/pdclust/layout-rr-failure.png
  doc/pdclust/layout-rr.drawio
  doc/pdclust/layout-rr.png
  doc/pdclust/layout-uniform.drawio
  doc/pdclust/layout-uniform.png
  doc/pdclust/permutation-uniform.drawio
  doc/pdclust/permutation-uniform.png
  doc/pdclust/permutation.drawio
  doc/pdclust/permutation.png
  doc/pdclust/pool.drawio
  doc/pdclust/pool.png
  doc/pdclust/tile.drawio
  doc/pdclust/tile.png
Labels: cla-signed, Exception

#2079 CORTX-33702: Codacy cleanup of markdown files
  doc/FOPFOM-Programming-Guide.md
  doc/HLD-OF-Motr-LNet-Transport.md
  doc/HLD-of-Catalogue-Service.md
  doc/Motr-Epochs-HLD.md
  doc/Motr-Lnet-Transport.md
  doc/Seagate-FDMI-HLD.md
  doc/motr-kv-app.md
  doc/motr-object-app.md
  scripts/provisioning/README.md
Labels: cla-signed

#2087 CORTX-33978- codacy cleanup: Fixed codacy formatting issues
  doc/FOPFOM-Programming-Guide.md
  doc/HLD-OF-Motr-LNet-Transport.md
  doc/HLD-of-Catalogue-Service.md
  doc/Motr-Lnet-Transport.md
  doc/Running_Motr_Across_a_Cluster.md
  doc/motr-object-app.md
Labels: cla-signed

#2084 CORTX-30953: [Codacy] fix shell directive problems
  fdmi/st/fdmi_test.sh
  m0t1fs/linux_kernel/st/common_service_fids_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_dix_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_io_config_params.sh
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh
  motr/st/utils/motr_fs.sh
  motr/st/utils/sns_repair_common_inc.sh
  net/test/run.sh
  scripts/provisioning/roles/motr-build/files/sclo-git212.sh
Labels: cla-signed

#1893 CORTX-30751: Codacy code cleanup (#1606)
  st/m0t1fs-buffsize-layout-change-test.sh
Labels: cla-signed, codacy, Status: Waiting to be Reviewed

#2057 CORTX-30751: This patch fixes some of the codacy warnings.
  scripts/install/opt/seagate/cortx/motr/sanity/cortx_lnet_sanity.sh
Labels: cla-signed, codacy, Status: Waiting to be Reviewed

#2089 CORTX-33978- codacy cleanup: Fixed codacy formatting issues
  doc/FOPFOM-Programming-Guide.md
  doc/HLD-of-Catalogue-Service.md
  doc/Running_Motr_Across_a_Cluster.md
  doc/motr-object-app.md
Labels: cla-signed

#1899 CORTX-30751: Codacy code cleanup (#1606)
  st/m0d-device-detach-test.sh
Labels: cla-signed, codacy, Status: Changes requested

#1932 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/m0t1fs_spiel_dix_common_inc.sh
Labels: cla-signed, codacy, Status: Waiting to be Reviewed, review required

#1898 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/spiel_multiple_confd.sh
Labels: cla-signed, codacy, Status: Changes requested

#2053 CORTX-30751: Codacy code cleanup (#1606)
  scripts/build-prep-1node-cortx-mgw.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#1965 CORTX-30751: Codacy code cleanup (#1606)
  scripts/provisioning/vmhost/prepare-host.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#2094 CORTX-33703: Codacy Cleanup
  2035.diff
Labels: cla-signed, Exception

#1957 CORTX-30751: Codacy code cleanup (#1606)
  scripts/provisioning/vmhost/super-cleanup.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed, review required

#1956 CORTX-30751: Codacy code cleanup (#1606)
  scripts/systemtap/kem/kem_run.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed, review required

#1855 CORTX-30751: Codacy code cleanup (#1606)
  m0t1fs/linux_kernel/st/m0t1fs_fsync_test.sh
Labels: cla-signed, needs-attention, rose

#2045 CORTX-30751: Codacy code cleanup
  scripts/demo/2015-10-dev2.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#1972 CORTX-30751: Codacy code cleanup (#1606)
  scripts/provisioning/vmhost/gci-create-cluster.sh
Labels: cla-signed, needs-attention, Status: Waiting to be Reviewed

#2004 setting async_disconnecting flag to avoid multiple async rpc disconn
  rm/rm.c
  rpc/link.c
  rpc/link.h
  rpc/service.c
Labels: cla-signed

#1920 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/m0t1fs_spiel_sns_common_inc.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#1896 CORTX-30751: Codacy code cleanup (#1606)
  st/stob_domain_recreate_on_corruption.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#2059 CORTX-32172: Fixes ADDB client logs to bundled it in rgw support bundle
  motr/client_init.c
Labels: cla-signed, Status: Draft

#2099 CORTX-33964: Improvement in code coverage job
  scripts/jenkins/code-coverage.groovy
Labels: cla-signed, Exception

#2105 cortx-34068: Fix m0_utils_common to point to correct path of m0hagen
  scripts/install/opt/seagate/cortx/motr/common/m0_utils_common.sh
Labels: cla-signed

#2104 st: fix failure of rpc cancel ST
  motr/st/utils/motr_rpc_cancel_test.sh
  scripts/m0
Labels: cla-signed

#1503 CORTX-27600 dtm0/log: initial implementation for dtx0 and pruner
  be/btree.c
  be/btree.h
  be/linux_kernel/stubs.c
  be/seg0.c
  be/seg0.h
  be/ut/helper.c
  cas/cas.c
  cas/cas.h
  cas/client.c
  cas/index_gc.c
  cas/service.c
  cas/ut/service_ut.c
  dtm0/Kbuild.sub
  dtm0/Makefile.sub
  dtm0/cfg_default.c
  dtm0/cfg_default.h
  dtm0/domain.c
  dtm0/domain.h
  dtm0/dtm0.c
  dtm0/dtm0.h
  dtm0/dtx0.c
  dtm0/dtx0.h
  dtm0/helper.c
  dtm0/helper.h
  dtm0/log.c
  dtm0/log.h
  dtm0/pruner.c
  dtm0/pruner.h
  dtm0/remach.h
  dtm0/service.c
  dtm0/service.h
  dtm0/tx_desc.c
  dtm0/ut/domain.c
  dtm0/ut/helper.c
  dtm0/ut/helper.h
  dtm0/ut/log.c
  dtm0/ut/main.c
  dtm0/ut/pruner.c
  fop/fom.c
  fop/fom.h
  fop/fom_generic.c
  lib/buf.h
  m0t1fs/linux_kernel/st/common_service_fids_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  motr/client_init.c
  motr/init.c
  motr/setup.c
  motr/st/utils/motr_local_conf.sh
  rpc/rpc_opcodes.h
  scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
  scripts/install/usr/libexec/cortx-motr/motr-cleanup
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
  ut/diter.cg
Labels: WIP, rose, Status: Draft

#1922 CORTX-30751: Codacy code cleanup (#1606)
  spiel/st/m0t1fs_spiel_sns_repair_quiesce.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#1857 CORTX-30753: Codacy code cleanup(#1608)
  m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh
  m0t1fs/linux_kernel/st/m0t1fs_rconfc_fail_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_restart_motr_service.sh
  m0t1fs/linux_kernel/st/m0t1fs_rlock_revoke.sh
  m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_server.sh
  m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1k_1f.sh
Labels: cla-signed, needs-attention, rose, Status: Waiting to be Reviewed

#2091 CORTX-32895: Fix spiel UTs for sns direct rebalance
  sns/cm/dtrebalance/trigger_fop.c
  sns/cm/trigger_fom.c
  sns/cm/trigger_fop_common.c
  spiel/cmd.c
  spiel/ut/spiel_ci_ut.c
  utils/m0confgen
Labels: cla-signed

#2097 CORTX-33057: Error handing for asserts.
  motr/setup.c
Labels: cla-signed

#1935 CORTX-30083: Fix Codacy issues under "net" directory
  net/test/st/run-1x1.sh
  net/test/st/st-bulk.sh
Labels: cla-signed, needs-attention, codacy, Status: Waiting to be Reviewed

#1936 CORTX-30083:Fix Codacy issues under "net" directory
  net/bulk_emulation/st/main.c
  net/bulk_emulation/st/ping.c
  net/net.c
  net/sock/sock.c
  net/test/demo/test.sh
  net/test/network.c
  net/test/node_bulk.c
  net/test/st/st-ping.sh
  net/test/ut/commands.c
  net/test/ut/slist.c
  net/ut/bulk_if.c
Labels: cla-signed, codacy, Status: Waiting to be Reviewed, review required

#1563 doc: fix pdclust link at CORTX-MOTR-ARCHITECTURE.md
  doc/CORTX-MOTR-ARCHITECTURE.md
Labels: cla-signed, needs-attention, rose, Status: Waiting to be Reviewed, Exception

#2101 CORTX-34044: Set btree watermarks logging level to M0_ALWAYS
  be/btree.c
Labels: cla-signed

#2098 CORTX-33740 : Analyse and fix memory leaks created by ctg module using s3 IOs.
  be/btree.c
  cas/ctg_store.c
  cas/ctg_store.h
  cas/index_gc.c
  cas/ut/service_ut.c
Labels: cla-signed

#2106 CORTX-30751: Codacy code cleanup (#1606)
  m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh
  m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_server.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1k_1f.sh
Labels: cla-signed

#2081 CORTX-33878_fix_alex_issues
  CONTRIBUTING.md
  SUPPORT.md
  doc/HLD-of-SNS-Repair.md
  doc/HLD-of-SNS-client.md
  doc/ISC-Service-User-Guide
  doc/ISC-Service-User-Guide.md
  doc/Motr-Lnet-Transport.md
  doc/RPC_Layer_Core.rst
  doc/Seagate-FDMI-HLD.md
  doc/faq.rst
  doc/fdmi_demo/demo-fdmi/m0-instance/Makefile
  doc/fdmi_demo/demo-fdmi/m0-instance/src/main.c
  doc/fdmi_demo/demo-fdmi/motr-client/Makefile
  doc/fdmi_demo/demo-fdmi/motr-client/src/main.c
  motr/ut/idx_dix.c
  scripts/jenkins/code-coverage-with-xperior-and-doxygen.groovy
Labels: cla-signed

#2076 CORTX-29983: UT and ST fixed with DTM0
  cas/service.c
  cas/ut/client_ut.c
  dtm0/fop.c
  dtm0/recovery.c
  layout/ut/plan.c
  motr/client_init.c
  motr/idx.c
  motr/st/mt/mt_fom.c
  motr/ut/idx_dix.c
Labels: cla-signed

#1981 dtm0: add online recovery DLD
  doc/Images/DTM0R Components and message flow.svg
  dtm0/dtm0-dld.c
  dtm0/dtm0-dld.h
  dtm0/log.c
Labels: needs-attention, Status: Merge Conflicts

#2108 CORTX-33834: Fixed rpc/conn.c m0_rpc_conn_ha_timer_start() memory leak
  rpc/conn.c
Labels: cla-signed

#1991 CORTX-33652: Add min_success parameter for index operations
  dix/req.c
  dix/req.h
  dix/ut/client_ut.c
  motr/client.h
  motr/client_internal.h
  motr/idx.c
  motr/idx.h
  motr/idx_dix.c
  motr/motr-pub.api
  motr/st/api.c
Labels: cla-signed, Status: Changes requested

#2109 CORTX-30074: Add support to m0_ha_sim for sns direct rebalance
  scripts/install/opt/seagate/cortx/motr/common/m0_spiel_sns_utils_common.sh
  scripts/install/opt/seagate/cortx/motr/libexec/m0_ha_sim
  utils/spiel/m0spiel
Labels: cla-signed
