Repository Seagate/cortx-motr, pull requests merged in 2022-07, with the labels that each got.

#1939 CORTX-30619: BTree documentation in github
  doc/HLD_NewBtree.md
Labels: cla-signed

#1947 Add btree_seg_header_validate while searching for sibling
  btree/btree.c
Labels: cla-signed

#1949 CORTX-30106: Changed data type of return value for read to ssize_t from size_t
  spiel/ut/spiel_conf_ut.c
Labels: cla-signed

#1961 CORTX-32856 fom: don't long hung foms of DTM requests
  fop/fom.c
Labels: cla-signed, review required

#1966 Support in motr_mini_prov.py to set BTree watermark values
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed, Exception

#1951 Start FDMI source dock timer fom only when FDMI filters are defined.
  fdmi/source_dock_fom.c
  fdmi/source_dock_internal.h
Labels: cla-signed, review required

#1791 Fix fdmi ut filterc
  fdmi/ut/filterc_ut.c
Labels: cla-signed, needs-attention, rose, Status: Waiting to be Reviewed

#1816 Fix namei ops cancel dist
  motr/client.c
  motr/client.h
  motr/idx_dix.c
Labels: cla-signed, needs-attention, rose, Status: Waiting to be Reviewed

#1959 CORTX-33537: allow degraded i/o for the new objects
  conf/pvers.c
  conf/ut/pvers.c
Labels: cla-signed, review required

#1971 Restart lnet systemd service when restarting lnet.
  utils/functions
Labels: cla-signed

#1940 CORTX-32040 : GITHUB ISSUE-./scripts/install-build-deps fails
  scripts/install-build-deps
Labels: cla-signed

#1980 dtm0/it: fix all2all CDF according to new changes in hare
  dtm0/it/all2all/cdf.yaml
Labels: cla-signed

#1973 DTM0: detect ctgdump failures in all2all script
  dtm0/it/all2all/all2all
Labels: cla-signed

#1967 DTM/recovery: Do not send REDO for transactions which happened after recovery started
  be/dtm0_log.c
  be/dtm0_log.h
  dtm0/recovery.c
  dtm0/recovery.h
  dtm0/ut/main.c
Labels: cla-signed

#1964 CORTX-31180: Validate the sdev id in the received CAS request.
  cas/service.c
Labels: cla-signed

#1985 Moving cortx-motr completely in user space hence user home directory.
  scripts/install/usr/lib/systemd/system/m0d@.service
  scripts/install/usr/lib/systemd/system/m0t1fs@.service
  scripts/install/usr/lib/systemd/system/motr-cleanup.service
  scripts/install/usr/lib/systemd/system/motr-client.service
  scripts/install/usr/lib/systemd/system/motr-kernel.service
  scripts/install/usr/lib/systemd/system/motr-mkfs.service
  scripts/install/usr/lib/systemd/system/motr-mkfs@.service
  scripts/install/usr/lib/systemd/system/motr-server-confd.service
  scripts/install/usr/lib/systemd/system/motr-server-ha.service
  scripts/install/usr/lib/systemd/system/motr-server@.service
  scripts/install/usr/lib/systemd/system/motr-trace@.service
  scripts/install/usr/lib/systemd/system/motr.service
  scripts/install/usr/libexec/cortx-motr/motr-kernel
  scripts/install/usr/libexec/cortx-motr/motr-mkfs
  scripts/install/usr/libexec/cortx-motr/motr-server
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
  scripts/install/usr/libexec/cortx-motr/motr-trace
Labels: cla-signed

#1974 CORTX-33586: ctgdump is crashing after new btree merge
  be/extmap.c
  cas/ctg_store.c
Labels: cla-signed

#1907 Changes in BE allocator to support no-clear mode during allocation.
  be/alloc.c
  be/alloc.h
  be/linux_kernel/stubs.c
  be/ut/alloc.c
  be/ut/main.c
  btree/btree.c
Labels: cla-signed

#1969 CORTX-33564: Fixed panic in rpc_session_cancelled() due to session state
  rpc/session.c
Labels: cla-signed

#1952 be/tool: Do not check the value of streq agains 0
  be/tool/main.c
Labels: cla-signed, needs-attention, review required

#1821 Fixing m0d-ut:cs-rconfc-fatal
  rm/st/wlock_helper.c
Labels: cla-signed

#1988 CORTX-27768 : ST to corrupt and detect data corruption
  .xperior/testds/motr-single_tests.yaml
  motr/st/utils/motr_di_corruption_detection_st.sh
  scripts/st.d/73motr-di-corruption-detection
Labels: cla-signed

#1787 go/mio: fix go get on the module
  bindings/go/go.mod
  bindings/go/mcp/mcp.go
  bindings/go/mkv/mkv.go
Labels: cla-signed, rose, Status: Waiting to be Reviewed, Exception

#1977 Fix Codacy Issues in shell script files under spiel dir.
  spiel/st/m0t1fs_spiel_dix_common_inc.sh
  spiel/st/m0t1fs_spiel_dix_repair.sh
  spiel/st/m0t1fs_spiel_dix_repair_quiesce.sh
  spiel/st/m0t1fs_spiel_sns_common_inc.sh
  spiel/st/m0t1fs_spiel_sns_repair.sh
  spiel/st/m0t1fs_spiel_sns_repair_quiesce.sh
  spiel/st/m0t1fs_spiel_st.sh
  spiel/st/spiel_multiple_confd.sh
Labels: cla-signed, Exception

#1984 CORTX-33021 : [F-58E]: Avoid redundant logs, improve log relevance: Motr
  lib/memory.c
Labels: cla-signed

#1674 [CORTX-30874]: Changed in Code owners for Motr
  CODEOWNERS
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1989 CORTX-33605: Support DTM0 recovery for CAS DEL operations
  cas/cas.h
  cas/service.c
  dtm0/fop.c
  motr/ut/idx_dix.c
Labels: cla-signed

#1986 CORTX-31893 : Optimize the node Capture for FF node format
  btree/btree.c
Labels: cla-signed

#1849 CORTX-29958: Tuning motr conf parameters based on resource limits
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed, Status: Checks failed

#2007 Adding path to take libisal from user home directory
  scripts/install/usr/libexec/cortx-motr/motr-mkfs
  scripts/install/usr/libexec/cortx-motr/motr-server
Labels: cla-signed

#2003 cas/service: forbid operating on sdevs in OFFLINE state
  cas/service.c
Labels: cla-signed

#1998 CORTX-33701: Fix memory leak related to m0_cob_bc_entries_dump()
  cob/cob.c
  cob/cob.h
  cob/ut/bytecount.c
  sss/process_foms.c
Labels: cla-signed

#1994 CORTX-33661 : Analyse and fix memory leaks for cob module using cob-ut and cob-foms-ut
  cob/cob.c
  cob/cob.h
  cob/ut/cob.c
  ioservice/cob_foms.c
  ioservice/io_foms.c
  ioservice/ut/bulkio_ut.c
  ioservice/ut/cob_foms.c
  sns/cm/storage.c
Labels: cla-signed

#2001 CORTX-33703- [Codacy code cleanup] occurrence: 133 pattern: warn list looseness is incorrect, such as being tight when it should
  README.md
  bindings/go/README.md
  doc/ADDB.md
  doc/CORTX-MOTR-ARCHITECTURE.md
  doc/DTM.md
  doc/FDMI-High-Level-Decomposition.md
  doc/FOPFOM-Programming-Guide.md
  doc/Running_Motr_Across_a_Cluster.md
  doc/Seagate-FDMI-Design-Notes.md
  doc/Seagate-FDMI-HLD.md
  doc/coding-style.md
Labels: Exception

#2005 CORTX-33681 fixing the Codacy issue of using type() instead of isinstance() for a typecheck
  scripts/provisioning/plugins/pretty_print.py
Labels: cla-signed

#2018 Revert "CORTX-33703: Codacy code cleanup (#2001)"
  README.md
  bindings/go/README.md
  doc/ADDB.md
  doc/CORTX-MOTR-ARCHITECTURE.md
  doc/DTM.md
  doc/FDMI-High-Level-Decomposition.md
  doc/FOPFOM-Programming-Guide.md
  doc/Running_Motr_Across_a_Cluster.md
  doc/Seagate-FDMI-Design-Notes.md
  doc/Seagate-FDMI-HLD.md
  doc/coding-style.md
Labels: cla-signed, Exception

#1983 CORTX-33627: Data pod logs are not shown in kubectl logs for motr containers
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#2013 CORTX-33718: Enable 37protocol st
  .xperior/testds/motr-single_tests.yaml
  st/protocol
  utils/functions
Labels: cla-signed

#1979 Markdown file upload
  doc/HLD-FOP-State-Machine.md
  doc/HLD-Layout-Schema.md
  doc/HLD-Meta-Data-Back-End.md
  doc/HLD-Resource-Management-Interface.md
  doc/HLD-Version-Numbers.md
  doc/HLD-fop-object-Iterator.md
  doc/HLD-of-Auxillary-Databases.md
  doc/HLD-of-Catalogue-Service.md
Labels: cla-signed

#2014 CORTX-26909 : Added shebang directive in autogen shell script.
  autogen.sh
  hsm/m0hsm_api.c
Labels: cla-signed

#2009 CORTX-33735: Gdb extensions throwing error
  scripts/gdb/gdb-extensions.py
Labels: cla-signed

#1993 CORTX-33667 Fixed codacy issues under addb-py files
  scripts/addb-py/filter.py
  scripts/addb-py/main.py
  scripts/addb-py/record.py
Labels: cla-signed
