Repository Seagate/cortx-motr, pull requests merged in 2022-04, with the labels that each got.

#1568 CORTX-29526: fix memleaks at data-path
  dix/req.c
  motr/client.c
  motr/cob.c
  motr/sync.c
Labels: cla-signed

#1576 FDMI file upload and reading-list.md file update
  doc/Seagate-FDMI-Design-Notes.md
  doc/Seagate-FDMI-HLD.md
  doc/reading-list.md
Labels: cla-signed

#1567 Swatid patch addb
  doc/ADDB.md
Labels: cla-signed

#1566 CORTX-29719: Set proper setup size for services other than ios and confd
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1575 CORTX-6081 - Port m0spiel utilities and ST to python3
  Makefile.am
  conf/st
  cortx-motr.spec.in
  scripts/install-motr-service
  scripts/provisioning/roles/base-os/tasks/main.yml
  spiel/st/m0t1fs_spiel_dix_common_inc.sh
  spiel/st/m0t1fs_spiel_sns_common_inc.sh
  spiel/st/m0t1fs_spiel_st.sh
  spiel/st/spiel_multiple_confd.sh
  st/m0d-device-detach-test.sh
  utils/functions
  utils/spiel/README
  utils/spiel/m0_bytecount_stats
  utils/spiel/m0_filesystem_stats
  utils/spiel/m0spiel
  utils/spiel/motr.c
Labels: cla-signed

#1588 CORTX-29183: Changes in Motr data structures to support Upgrade
  cas/ctg_store.c
  cas/ctg_store.h
Labels: cla-signed

#1584 CORTX-30135: m0worklad script changes for k8s
  scripts/workload/m0workload
Labels: cla-signed

#1571 CORTX-29713: m0_conf_pver_status() now returns CRITICAL if max failures reached at any level
  conf/pvers.c
Labels: cla-signed

#1600 Change user-visible name of motr/ut/client.c UT suite.
  motr/io.c
  motr/ut/client.c
Labels: cla-signed

#1602 CORTX-29857: GITHUB ISSUE-list unit benchmarks failed.
  lib/ut/timer.c
Labels: cla-signed

#1489 CORTX-28542_convert_kernel_based_spiel_ST_to_user_mode
  .xperior/testds/motr-single_tests.yaml
  motr/st/utils/spiel_sns_motr_repair.sh
  motr/st/utils/spiel_sns_motr_repair_quiesce.sh
  scripts/st.d/71spiel-sns-motr-repair
  scripts/st.d/72spiel-sns-motr-repair-quiesce
  spiel/st/m0t1fs_spiel_sns_common_inc.sh
Labels: cla-signed

#1616 CORTX-30717 motr_setup help typo
  scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Labels: cla-signed

#1623 CORTX-29739: Rename cvg_count and storage_set_count keys
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Labels: cla-signed

#1556 EOS-28989: Updated STs to use the transport specific address format.
  m0t1fs/linux_kernel/st/m0t1fs_failure_after_sns_repair_quiesce.sh
  m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh
  m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1k_1f.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1n_1f.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort_quiesce.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_ios_fail.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_mf.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_quiesce.sh
  m0t1fs/linux_kernel/st/m0t1fs_sns_repair_shutdown.sh
  motr/st/utils/sns_repair_motr_1f.sh
  motr/st/utils/sns_repair_motr_1k_1f.sh
  motr/st/utils/sns_repair_motr_1n_1f.sh
  motr/st/utils/sns_repair_motr_abort.sh
  motr/st/utils/sns_repair_motr_abort_quiesce.sh
  motr/st/utils/sns_repair_motr_ios_fail.sh
  motr/st/utils/sns_repair_motr_mf.sh
  motr/st/utils/sns_repair_quiesce.sh
  motr/st/utils/sns_repair_shutdown.sh
  spiel/st/m0t1fs_spiel_sns_repair.sh
  spiel/st/m0t1fs_spiel_sns_repair_quiesce.sh
Labels: cla-signed

#1645 CORTX-30548: Load all required nodes before acquiring tree Lock in btree get op
  btree/btree.c
Labels: cla-signed

#1647 CORTX-30821 : spiel-ut binds the same address twice.
  conf/ut/common.h
  spiel/ut/spiel_ut_common.h
Labels: cla-signed

#1634 conf/confd_stob.c: use aligned free for aligned allocations.
  conf/confd_stob.c
Labels: cla-signed

#1631 motr/ut: use aligned free for aligned allocations.
  motr/ut/client.h
  motr/ut/io_dummy.c
  motr/ut/io_nw_xfer.c
Labels: cla-signed

#1628 CORTX-30728 cas/client: fix memory corruption issue
  cas/client.c
  dix/req.c
Labels: cla-signed

#1625 CORTX-30090: Fix address format changes for m0_ha_sim in k8s
  scripts/install/opt/seagate/cortx/motr/common/m0_sns_utils_common.sh
  scripts/install/usr/libexec/cortx-motr/motr-service.functions
Labels: cla-signed

#1593 motr/client: fix some index ops api documentation
  motr/client.h
Labels: cla-signed

#1632 lib/user_space: use sigsetjmp() and siglongjmp().
  lib/user_space/thread.h
  lib/user_space/ucookie.c
Labels: bug, cla-signed

#1633 fdmi/ut: use m0_strdup().
  fdmi/ut/sd_apply_filter.c
  fdmi/ut/sd_send_not.c
Labels: bug, cla-signed

#1673 m0_ut_stob_fini(): finalise the domain properly.
  ut/stob.c
Labels: cla-signed

#1579 CORTX-29855: Add support to specify build options in Jenkins code coverage job
  scripts/jenkins/code-coverage.groovy
Labels: cla-signed

#1639 m0ut.c: LNet unit tests should depend on ENABLE_LUSTRE.
  ut/m0ut.c
Labels: bug, cla-signed, libfabric_integration

#1640 Finalise dtm0 fop types in m0_dtm0_stype_fini().
  dtm0/service.c
Labels: bug, cla-signed, DTM0

#1641 cas/ut: fix memory leak at meta_fop_submit()
  cas/ut/service_ut.c
Labels: bug, cla-signed

#1642 Use unique stob domain pathname.
  stob/ut/domain.c
Labels: cla-signed

#1655 go/mio: fix hang when motr i/o op returns error
  bindings/go/mio/mio.go
Labels: cla-signed

#1667 layout-access-plan-ut: make it repeatable
  layout/ut/plan.c
Labels: bug, cla-signed

#1680 Add CAS FOM state name in m0trace
  cas/service.c
Labels: cla-signed

#1599 Initialise ->op_pending_tx* fields in m0_op_init().
  motr/client.c
Labels: cla-signed

#1670 parity-math-ut: fix repeated execution
  sns/parity_math.c
  sns/ut/parity_math_ut.c
Labels: cla-signed

#1665 net/test/node_bulk.c: fix a race with asynchronous completion call-back
  net/test/node_bulk.c
Labels: bug, cla-signed, libfabric_integration

#1664 CORTX-30802: PI6 motr QSG Verification
  doc/Quick-Start-Guide.rst
Labels: cla-signed

#1589 CORTX-27770: Log rotation and compression for the motr log files
  Makefile.am
  cortx-motr.spec.in
  scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
  scripts/install/opt/seagate/cortx/motr/libexec/motr_mini_prov_logrotate.sh
Labels: cla-signed

#1651 CORTX-30423: M0_ENF_META support for m0kv
  motr/m0kv/cmd_main.c
  motr/m0kv/index.h
  motr/m0kv/index_op.c
  motr/m0kv/index_parser.c
Labels: cla-signed

#1656 libfab.c:libfab_domain_params_get() free "fi" only when it was allocated
  net/libfab/libfab.c
Labels: bug, cla-signed, libfabric_integration

#1699 libfab_poller(): make sure the end-point is not freed while being used.
  net/libfab/libfab.c
Labels: cla-signed

#1685 CORTX-30109: Motr Support bundle should contain sns/dix config params.
  utils/m0reportbug
Labels: cla-signed

#1597 CORTX-29819: Consider REPAIRED state of devices while deciding pver health for bytecount
  conf/pvers.c
Labels: cla-signed

#1675 new README.md upload
  Makefile.am
  README.md
  archives/ADDB_Monitoring.rst
  archives/README.rst
  cortx-motr.spec.in
  doc/motr-in-prose.md
Labels: cla-signed

#1702 CORTX-30429: M0_ENF_META support for m0crate
  motr/m0crate/crate_client.h
  motr/m0crate/crate_index.c
  motr/m0crate/crate_io.c
  motr/m0crate/parser.c
  motr/st/utils/m0crate_st_workloads.yaml
Labels: cla-signed
